- tests/networking/nethelper/nethelper.go
- tests/networking/netparameters/parameters.go
- tests/networking/tests/networking_default_network.go
Renamed default network test case
Removed partner pod support
Refactored netgative disconnected test case
> Adjusted networking suite to the new tnf design

- tests/networking/tests/networking_default_network.go
Removed 2 test cases from networking suite:
1. no ping binary - negative
2. no ip binary - skip
Due to the latest change these tests are not relevant anymore
> Removed 2 test cases from networking suite

- scripts/run-tests.sh
- tests/globalhelper/deployment.go
- tests/globalhelper/helper.go
- tests/lifecycle/lifecycle_suite_test.go
- tests/lifecycle/lifehelper/lifehelper.go
- tests/lifecycle/lifeparameters/parameters.go
- tests/lifecycle/tests/lifecycle_shutdown.go
- tests/networking/nethelper/nethelper.go
- tests/utils/deployment/deployment.go
47311, 47315 lifecycle shutdown tests
> Automate two lifecycle-shutdown preStop flag tests

- tests/networking/nethelper/nethelper.go
- tests/networking/netparameters/parameters.go
- tests/networking/tests/networking_multus_links.go
- tests/networking/tests/networking_multus_links_negative.go
- tests/utils/daemonset/daemonset.go
- tests/utils/deployment/deployment.go
Added TC Networking custom namespace, custom daemonset 3 pods with skip label [skip]
Added TC Networking custom namespace, custom deployment and daemonset 3 pods with skip label[skip]
Added TC Networking custom namespace, custom deployment and daemonSet 3 pods, daemonSet has skip label
Added TC Networking custom namespace, custom deployment 3 pods, 2 NADs, multiple Multus interfaces on deployment
Added TC Networking custom namespace, custom deployment and daemonset 3 pods, 2 NADs, multiple Multus interfaces on deployment no connectivity via secondary interface[negative]
Fixed Multus test cases names
> Added 5 new test cases to networking multus suite

- scripts/golangci-lint.sh
https://github.com/test-network-function/test-network-function/pull/641
> Upgrade GolangCI-lint to v1.44.2

- tests/affiliatedcertification/affiliatedcertparameters/parameters.go
- tests/affiliatedcertification/tests/affiliated_certification_operator.go
and increased timeout for operator deployment
> Fixed operator deployment namespace

- tests/lifecycle/tests/lifecycle_statefulset_scaling.go
This PR contains a statefulset-scaling test (45439)
> Automate statefulSet-scaling test

- tests/lifecycle/lifecycle_suite_test.go
- tests/lifecycle/tests/lifecycle_deployment_scaling.go
- tests/lifecycle/tests/lifecycle_image_pull_policy.go
- tests/lifecycle/tests/lifecycle_pod_high_availability.go
- tests/lifecycle/tests/lifecycle_pod_owner_type.go
- tests/lifecycle/tests/lifecycle_pod_recreation.go
- tests/lifecycle/tests/lifecycle_pod_scheduling.go
- tests/lifecycle/tests/lifecycle_shutdown.go
This PR is for consistency and contains fixes such as vars names and better step description readability.
> Fix vars names for consistency

- tests/lifecycle/tests/lifecycle_liveness.go
- tests/utils/deployment/deployment.go
- tests/utils/pod/pod.go
- tests/utils/statefulset/statefulset.go
This PR contains lifecycle/liveness test cases (50053, 50054, 50055, 50056, 50057, 50058)
> Automated lifecycle/liveness tests

- tests/lifecycle/lifehelper/lifehelper.go
- tests/lifecycle/tests/lifecycle_liveness.go
- tests/lifecycle/tests/lifecycle_pod_owner_type.go
- tests/lifecycle/tests/lifecycle_readiness.go
- tests/utils/deployment/deployment.go
- tests/utils/pod/pod.go
- tests/utils/statefulset/statefulset.go
This PR contains lifecycle/readiness test cases.
> Automated lifecycle/readiness tests

- tests/affiliatedcertification/affiliatedcertparameters/parameters.go
Updates the test case name parameters to match the names in the new repo.
> changed affiliated-certification test case names

- tests/affiliatedcertification/affiliated_certification_suite_test.go
- tests/affiliatedcertification/affiliatedcerthelper/affiliatedcerthelper.go
- tests/affiliatedcertification/affiliatedcertparameters/parameters.go
- tests/affiliatedcertification/tests/affiliated_certification_operator.go
- tests/globalhelper/reporthelper.go
- tests/globalhelper/runhelper.go
- tests/globalparameters/globalparameters.go
- tests/lifecycle/lifeparameters/parameters.go
- tests/utils/config/config.go
Adjusted affiliatedcertification suite to the new
cnf-certification-project
Refactored lifecycle parameters and removed redundant vars
> Refactored affiliatedcertification suite

- README.md
- tests/globalhelper/runhelper.go
- tests/lifecycle/tests/lifecycle_pod_high_availability.go
- tests/lifecycle/tests/lifecycle_pod_recreation.go
- tests/networking/nethelper/nethelper.go
- tests/utils/deployment/deployment.go
- tests/utils/nodes/nodes.go
Found some easy typos to correct.
> Typo correction

- .github/workflows/makefile.yml
https://github.com/golang/go/issues?q=milestone%3AGo1.17.9+label%3ACherryPickApproved
> Update Go to 1.17.9

- tests/affiliatedcertification/affiliatedcertparameters/parameters.go
- tests/affiliatedcertification/tests/affiliated_certification_container.go
- tests/globalhelper/helper.go
- tests/globalparameters/globalparameters.go
Changed container info fields for tnf config
and values used in test cases
to reflect the current functionality of the container certification test
> Updates to container certification test cases to match new functionality

- scripts/golangci-lint.sh
https://github.com/golangci/golangci-lint/releases/tag/v1.46.2
> Upgrade golangci-lint to 1.46.2

- .github/workflows/makefile.yml
https://releases.ubuntu.com/22.04/
LTS 22.04 is available "Jammy Jellyfish".
> Upgrade Ubuntu release to 22.04

- tests/accesscontrol/helper/helper.go
- tests/accesscontrol/parameters/parameters.go
- tests/accesscontrol/tests/access_control_pod_automount_service_account_token.go
- tests/utils/deployment/deployment.go
infrastructure + four test cases
> Access control pod automount service account token

- tests/globalhelper/helper.go
- tests/globalhelper/init.go
- tests/networking/helper/helper.go
- tests/networking/networking_suite_test.go
- tests/platformalteration/helper/helper.go
- tests/platformalteration/parameters/parameters.go
- tests/platformalteration/tests/platform_alteration_hugepages_config.go
- tests/utils/crd/crd.go
> Automated platform-alteration-hugepages-config tcs

- tests/platformalteration/parameters/parameters.go
The tc used to fail due to an image pull limit, Thus I have changed the source of the image.
> Changed image source in parameters.go

- tests/affiliatedcertification/affiliated_certification_suite_test.go
- tests/affiliatedcertification/helper/helper.go
- tests/affiliatedcertification/parameters/parameters.go
Removed and re-added label from operator used by other test suite before and after affiliated-certification suite.
> removed and re-added label from operator used by other test suite

- .github/workflows/makefile.yml
Related:
- https://github.com/test-network-function/cnf-certification-test/pull/391
- https://github.com/test-network-function/cnf-certification-test-partner/pull/141
> Update Go to 1.18.5

- tests/lifecycle/parameters/parameters.go
Updated lifecycle liveness and readiness test case names to match new names in cnf-certification-test
> Updated lifecycle liveness and readiness test case

- README.md
- tests/platformalteration/tests/platform_alteration_hugepages_config.go
> Add access-control to README, Fix tc name in platform-alteration/hugepages config

- tests/accesscontrol/tests/access_control_pod_host_ipc.go
- tests/accesscontrol/tests/access_control_pod_host_network.go
- tests/accesscontrol/tests/access_control_pod_host_pid.go
- tests/utils/deployment/deployment.go
Reverts test-network-function/cnfcert-tests-verification#133
> Revert "Changed deployment spec-changing funcs that don't use pointers for values to return deployment pointer"

- tests/lifecycle/helper/helper.go
- tests/lifecycle/lifecycle_suite_test.go
- tests/lifecycle/parameters/parameters.go
- tests/lifecycle/tests/lifecycle_container_shutdown.go
- tests/lifecycle/tests/lifecycle_deployment_scaling.go
- tests/lifecycle/tests/lifecycle_image_pull_policy.go
- tests/lifecycle/tests/lifecycle_liveness.go
- tests/lifecycle/tests/lifecycle_persistent_volume_reclaim_policy.go
- tests/lifecycle/tests/lifecycle_pod_high_availability.go
- tests/lifecycle/tests/lifecycle_pod_owner_type.go
- tests/lifecycle/tests/lifecycle_pod_recreation.go
- tests/lifecycle/tests/lifecycle_pod_scheduling.go
- tests/lifecycle/tests/lifecycle_readiness.go
- tests/lifecycle/tests/lifecycle_statefulset_scaling.go
- tests/utils/deployment/deployment.go
- tests/utils/namespaces/namespaces.go
- tests/utils/persistentvolume/persistentvolume.go
- tests/utils/persistentvolumeclaim/persistentvolumeclaim.go
- tests/utils/pod/pod.go
- tests/utils/replicaset/replicaset.go
Automated 54201, 54202, 54203, 54204, 54206, 54207
Add lifecycle pv relcaim tc, improve lifecycle suite readability and consistency.
> Add lifecycle pv relcaim tc, improve lifecycle suite readability

- .github/workflows/makefile.yml
- .golangci.yml
- go.mod
https://groups.google.com/g/golang-announce/c/x49AQzIVX-s
Related to: https://github.com/test-network-function/cnf-certification-test/pull/531
> Upgrade Go to v1.19.1

- tests/lifecycle/parameters/parameters.go
- tests/lifecycle/tests/lifecycle_cpu_isolation.go
- tests/lifecycle/tests/lifecycle_persistent_volume_reclaim_policy.go
- tests/lifecycle/tests/lifecycle_startup_probe.go
- tests/utils/deployment/deployment.go
- tests/utils/pod/pod.go
- tests/utils/statefulset/statefulset.go
Automated 54808, 54809, 54810, 54811, 54812, 54813, 54814, 54815.
Fixed tcs names in parameters.go
> Add lifecycle-startup-probe verification tc's

- tests/lifecycle/parameters/parameters.go
- tests/lifecycle/tests/lifecycle_container_startup.go
- tests/utils/deployment/deployment.go
- tests/utils/pod/pod.go
- tests/utils/statefulset/statefulset.go
Automated 55910,55911,55913,55914,55916.
> Automated lifecycle container-startup verification scenarios

- tests/globalhelper/helper.go
- tests/globalhelper/reporthelper.go
- tests/globalhelper/runhelper.go
- tests/utils/config/config.go
In order to debug CI failures we need the claim reports as well.
> Added claim to reports folder

- tests/lifecycle/tests/lifecycle_affinity_required_pods.go
Reverts test-network-function/cnfcert-tests-verification#174
> Revert "Disabled affinity req pods tc for debugging purposes"

- tests/platformalteration/parameters/parameters.go
- tests/platformalteration/tests/platform_alteration_ocp_lifecycle.go
There is no way to change the environment on this tc, we should only expect it to pass.
> Add ocp-lifecycle test

- Makefile
- scripts/install-ginkgo.sh
- tests/platformalteration/helper/helper.go
- tests/platformalteration/parameters/parameters.go
- tests/platformalteration/tests/platform_alteration_service_mesh.go
Fixed the MakeFile.
Fixed install-ginkgo script.
Added the service-mesh-usage tcs.
> added platform-alteration-service-mesh tcs

- .github/workflows/makefile.yml
https://groups.google.com/g/golang-announce/c/L_3rmdT0BMU
> Update Go to v1.19.4

- scripts/install-ginkgo.sh
This should match the current go.mod version.
> Update Ginkgo manual install to 2.8.1

- scripts/golangci-lint.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/863
> Update GolangCI-lint to v1.51.1

- tests/accesscontrol/helper/helper.go
- tests/globalhelper/daemonset.go
- tests/globalhelper/deployment.go
- tests/globalhelper/helper.go
- tests/globalhelper/poddisruptionbudget.go
- tests/globalhelper/replicaset.go
- tests/globalhelper/runtimeclass.go
- tests/globalhelper/statefulset.go
- tests/lifecycle/helper/helper.go
- tests/lifecycle/tests/lifecycle_image_pull_policy.go
- tests/networking/helper/helper.go
- tests/utils/daemonset/daemonset.go
- tests/utils/deployment/deployment.go
- tests/utils/namespaces/namespaces.go
- tests/utils/poddisruptionbudget/poddisruptionbudget.go
- tests/utils/replicaset/replicaset.go
- tests/utils/runtimeclass/runtimeclass.go
- tests/utils/service/service.go
- tests/utils/statefulset/statefulset.go
Similar to changes done:
- https://github.com/test-network-function/cnf-certification-test/pull/814
- https://github.com/test-network-function/cnf-certification-test/pull/177
- https://github.com/test-network-function/cnf-certification-test/pull/618
> Import naming convention update

- scripts/run-tests.sh
Turns out this is what was preventing the tests from running.
> Removed quotes around suite name variables

- .github/workflows/makefile.yml
Related to: https://github.com/test-network-function/cnf-certification-test/pull/924
> Update Go to 1.20.2

- tests/affiliatedcertification/parameters/parameters.go
- tests/affiliatedcertification/tests/affiliated_certification_invalid_operator.go
- tests/affiliatedcertification/tests/affiliated_certification_operator.go
Updated infinibox version,
replaced artifactory operator with instana-agent,
changed timeout to 5 min,
added skip for uncertified version cases
> Fixes for test operator installation

- tests/platformalteration/tests/platform_alteration_service_mesh.go
Added istio operator installation before service mesh tests
> Added istio operator installation

- README.md
- config/testconfig.yaml
- tests/platformalteration/tests/platform_alteration_service_mesh.go
- tests/utils/config/config.go
Includes 
* Information about newly introduced variables for local testing
* New dev / testing config file
* Updated ReadMe
* Removed unnecessary information
> Improve testing steps

- tests/globalhelper/runhelper.go
- tests/globalparameters/globalparameters.go
- tests/performance/helper/helper.go
- tests/performance/parameters/parameters.go
- tests/performance/performance_suite_test.go
- tests/performance/tests/exclusive_cpu_pools.go
- tests/utils/pod/pod.go
Includes : 
- A new test suite called `performance` 
- Test case : Exclusive CPU pool
> Performance suite - Test Exclusive CPU pool

- .github/workflows/makefile.yml
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/994
> Update Go to v1.20.3

- tests/platformalteration/tests/platform_alteration_service_mesh.go
Turns out I left some pipes lying around
> Fix istio install and uninstall scripts

- scripts/golangci-lint.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1058
> Update GolangCI to v1.52.2

- .golangci.yml
- scripts/golangci-lint.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1156
> Update GolangCI to 1.53.2

- .github/workflows/makefile.yml
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1165
> Update Go to v1.20.5

- tests/platformalteration/tests/platform_alteration_service_mesh.go
https://github.com/istio/istio/releases/tag/1.18.0
> Update Istio to v1.18.0

- tests/accesscontrol/parameters/parameters.go
- tests/accesscontrol/tests/access_control_pod_automount_service_account_token.go
- tests/utils/deployment/deployment.go
added valid service account to pods in automount service account token test cases
> added valid service account to pods

- tests/platformalteration/tests/platform_alteration_service_mesh.go
https://github.com/istio/istio/releases/tag/1.18.1
> Update Istio to v1.18.1

- tests/lifecycle/tests/lifecycle_affinity_required_pods.go
- tests/lifecycle/tests/lifecycle_container_shutdown.go
- tests/lifecycle/tests/lifecycle_cpu_isolation.go
- tests/lifecycle/tests/lifecycle_persistent_volume_reclaim_policy.go
- tests/lifecycle/tests/lifecycle_pod_high_availability.go
- tests/lifecycle/tests/lifecycle_pod_recreation.go
- tests/utils/crd/crd.go
> Remove the ampersand from strings

- tests/accesscontrol/helper/helper.go
- tests/globalhelper/daemonset.go
- tests/globalhelper/deployment.go
- tests/globalhelper/helper.go
- tests/globalhelper/networkpolicy.go
- tests/globalhelper/pod.go
- tests/globalhelper/poddisruptionbudget.go
- tests/globalhelper/rbac.go
- tests/globalhelper/replicaset.go
- tests/globalhelper/runtimeclass.go
- tests/globalhelper/statefulset.go
- tests/lifecycle/helper/helper.go
- tests/networking/helper/helper.go
- tests/observability/helper/helper.go
- tests/performance/helper/helper.go
- tests/platformalteration/helper/helper.go
- tests/platformalteration/tests/platform_alteration_boot_params.go
- tests/platformalteration/tests/platform_alteration_sysctl_config.go
- tests/utils/cluster/cluster.go
- tests/utils/crd/crd.go
- tests/utils/namespaces/namespaces.go
- tests/utils/nodes/nodes.go
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1216 
To conform with the other repos, switch everything to `context.TODO()` instead of `context.Background()`.  They are the same function.
> Switch context.Background to context.TODO

- tests/affiliatedcertification/helper/operator.go
- tests/globalhelper/daemonset.go
- tests/globalhelper/deployment.go
- tests/globalhelper/helper.go
- tests/globalhelper/networkpolicy.go
- tests/globalhelper/pod.go
- tests/globalhelper/poddisruptionbudget.go
- tests/globalhelper/replicaset.go
- tests/globalhelper/runtimeclass.go
- tests/globalhelper/statefulset.go
- tests/lifecycle/helper/helper.go
- tests/performance/helper/helper.go
Handle resources that already exist.
> Handle Create() errors

- tests/globalhelper/runhelper.go
- tests/lifecycle/tests/lifecycle_image_pull_policy.go
Removing some contractions I came across.
Similar to: https://github.com/test-network-function/cnf-certification-test/pull/264
> Fix some small typos

- playbooks/fedora-setup.yml
- playbooks/inventory.ini
Also adds the inventory file after discussion with @rdavid
> Add daily cron for docker system prune

- .github/workflows/makefile.yml
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1315
> Update Go to v1.20.7

- tests/globalhelper/helper.go
https://github.com/test-network-function/cnf-certification-test/actions/runs/5867229838/job/15907550374#step:12:41
> Fix empty operator labels

- tests/networking/helper/helper.go
- tests/networking/tests/networking_multus_links.go
Correcting a typo I found while playing around in the networking suite.
> Deamonset --> Daemonset

- go.mod
- go.sum
Follow up to #429 I accidentally forgot to update the go.mod
> Forgot to update the go.mod

- scripts/golangci-lint.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1367
> Update GolangCI-lint to v1.54.2

- Makefile
- scripts/run-tests.sh
Not all the suites are ready to be launched in parallel.
> Bug fix: disallow global parallel run of the Ginkgo suites

- tests/globalhelper/init.go
- tests/globalhelper/reporthelper.go
- tests/lifecycle/tests/lifecycle_cpu_isolation.go
- tests/lifecycle/tests/lifecycle_crd_scaling.go
- tests/lifecycle/tests/lifecycle_deployment_scaling.go
- tests/lifecycle/tests/lifecycle_persistent_volume_reclaim_policy.go
- tests/lifecycle/tests/lifecycle_storage_required_pods.go
#465 didn't clear out the contents of the directory first and was left with errors saying how the directory wasn't empty.
> Fix the cleanup

- tests/performance/helper/helper.go
- tests/performance/performance_suite_test.go
- tests/performance/tests/exclusive_cpu_pools.go
- tests/performance/tests/rt_app_no_exec_probes.go
- tests/performance/tests/rt_exclusive_cpu_pool_scheduling_policy.go
- tests/performance/tests/rt_isolated_cpu_pool.go
- tests/performance/tests/shared-cpu-pool-non-rt-scheduling-policy.go
> Enable parallel performance suite

- tests/accesscontrol/parameters/parameters.go
- tests/accesscontrol/tests/access_control_crd_roles.go
- tests/accesscontrol/tests/access_control_pod_role_bindings.go
- tests/globalhelper/rbac.go
- tests/lifecycle/helper/helper.go
- tests/lifecycle/tests/lifecycle_crd_scaling.go
- tests/utils/crd/crd.go
https://issues.redhat.com/browse/CNFCERT-622
* Implement negative tests for CRD roles
* Refactoring of role and custom resource creation
> QE Coverage : Accesscontrol - CRD Roles

- .github/workflows/makefile.yml
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1387
> Update Go to v1.21.1

- tests/observability/helper/helper.go
- tests/observability/observability_suite_test.go
- tests/observability/parameters/parameters.go
- tests/observability/tests/container_logging.go
- tests/observability/tests/crd_status.go
- tests/observability/tests/pod_disruption_budget.go
- tests/observability/tests/termination_policy.go
> Enable observability suite in parallel

- Makefile
- README.md
- tests/platformalteration/helper/helper.go
- tests/platformalteration/platform_alteration_suite_test.go
- tests/platformalteration/tests/platform_alteration_base_image.go
- tests/platformalteration/tests/platform_alteration_boot_params.go
- tests/platformalteration/tests/platform_alteration_hugepages_1g.go
- tests/platformalteration/tests/platform_alteration_hugepages_2m.go
- tests/platformalteration/tests/platform_alteration_hugepages_config.go
- tests/platformalteration/tests/platform_alteration_is_redhat_release.go
- tests/platformalteration/tests/platform_alteration_is_selinux_enforcing.go
- tests/platformalteration/tests/platform_alteration_ocp_lifecycle.go
- tests/platformalteration/tests/platform_alteration_ocp_node_os.go
- tests/platformalteration/tests/platform_alteration_service_mesh.go
- tests/platformalteration/tests/platform_alteration_sysctl_config.go
- tests/platformalteration/tests/platform_alteration_tainted_node_kernel.go
There are a lot of skipped tests when it comes to Kind clusters in this suite.
> Enable parallel platform-alteration suite

- tests/globalparameters/globalparameters.go
Follow up to: https://github.com/test-network-function/cnf-certification-test/pull/1416
> Remove certified operator field

- tests/utils/deployment/deployment.go
- tests/utils/deployment/deployment_test.go
Similar to #490 
Covered all of the funcs except: 
- `RedefineWith2MiHugepages`
- `RedefineWith1GiHugepages`
> Add deployment unit tests

- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1504
> Update Go to v1.21.2

- tests/accesscontrol/tests/access_control_namespace_resource_quota.go
#524 broke this test with a copy-paste.
> Fix negative access-control test case

- tests/affiliatedcertification/tests/affillated_certification_helm_chart.go
Temporarily disable these two tests on Kind while I debug them.  Follow up to #523
> Skip helm chart tests on Kind

- tests/affiliatedcertification/tests/affiliated_certification_helm_version.go
Similar to: #530 
These tests also fail on Kind and need some additional debugging.
> Disable helm version tests on Kind

- tests/lifecycle/parameters/parameters.go
- tests/lifecycle/tests/lifecycle_storage_provisioner.go
Renaming test case due to: https://github.com/test-network-function/cnf-certification-test/pull/1507
> renaming test case

- tests/globalhelper/deployment.go
- tests/globalhelper/deployment_test.go
- tests/utils/daemonset/daemonset.go
- tests/utils/deployment/deployment.go
- tests/utils/deployment/deployment_test.go
- tests/utils/replicaset/replicaset.go
- tests/utils/statefulset/statefulset.go
Pulled from changes made in #536 
Similar to changes made to daemonsets in #534
> Add ReadyReplicas; decrease minReadySeconds

- tests/globalhelper/statefulset.go
- tests/globalhelper/statefulset_test.go
- tests/lifecycle/tests/lifecycle_container_startup.go
- tests/lifecycle/tests/lifecycle_liveness.go
- tests/lifecycle/tests/lifecycle_pod_owner_type.go
- tests/lifecycle/tests/lifecycle_readiness.go
- tests/lifecycle/tests/lifecycle_startup_probe.go
- tests/observability/tests/pod_disruption_budget.go
- tests/observability/tests/termination_policy.go
- tests/platformalteration/tests/platform_alteration_is_redhat_release.go
Similar to: #536 and #534 
Adds some assertions for modifications done to statefulsets.
> Add assertions for statefulSets

- tests/accesscontrol/tests/access_control_crd_roles.go
Skip these tests if `cr-scale-operator` is not installed.
> Move skip to BeforeEach; organize AfterEach

- tests/operator/operator_suite_test.go
Easy change for allowing the operator suite to run smoothly in OCP.
> Fix operator suite for OCP

- .github/workflows/makefile.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1558
> Update Go to v1.21.3

- tests/platformalteration/tests/platform_alteration_service_mesh.go
https://github.com/istio/istio/releases/tag/1.19.3
> Update istio to v1.19.3

- tests/globalhelper/daemonset_test.go
- Switch `glog.Fatal` to `glog.Error` to prevent fatal errors from occurring where they are not needed.
- Add unit tests for `GetDaemonSetPullPolicy` and `GetRunningDaemonset` functions.
> Add unit tests for daemonset.go

- tests/globalhelper/namespaces.go
- tests/globalhelper/namespaces_test.go
Unit tests for `namespaces.go`.  During the writing of these unit tests, I'm pretty sure the calls to `DeleteCollection` do not work or at least when I call them within the unit tests they weren't doing anything.  So I had to modify them to brute force delete the resources within the namespace.
> Add unit tests for namespaces.go

- tests/utils/rbac/rbac_test.go
Small PR to add some unit testing surrounding the rbac.go functions.
> Add unit tests for utils/rbac.go

- tests/lifecycle/tests/lifecycle_affinity_required_pods.go
- tests/utils/pod/pod.go
- tests/utils/pod/pod_test.go
PR to add unit tests for all of the funcs we use concerning pods.
> Add unit tests for utils/pod.go

- scripts/golangci-lint.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1575
> Update GolangCI-lint v1.55.1

- scripts/run-tests.sh
Just giving the tests extra wiggle room.
> Increase flaky retries from 2 to 3

- tests/utils/daemonset/daemonset_test.go
`coverage: 100.0% of statements`
> Add daemonset unit tests

- tests/utils/config/config_test.go
- tests/utils/installplan/installplan_test.go
- tests/utils/nad/nad_test.go
- tests/utils/networkpolicy/networkpolicy_test.go
- tests/utils/operator/operator_test.go
- tests/utils/persistentvolume/persistentvolume_test.go
- tests/utils/persistentvolumeclaim/persistentvolumeclaim_test.go
- tests/utils/replicaset/replicaset_test.go
- tests/utils/resourcequota/resourcequota_test.go
- tests/utils/runtimeclass/runtimeclass_test.go
- tests/utils/service/service_test.go
- tests/utils/statefulset/statefulset_test.go
A bunch more unit tests for various packages under the `utils` folder.
> Add various unit tests under utils

- tests/globalhelper/statefulset.go
Make sure that both `AvailableReplicas` and `ReadyReplicas` match the desired replicas spec.
> Add check for AvailableReplicas for statefulsets

- scripts/delete-namespaces.sh
Add `cnf-suite` to the delete-namespaces.sh script so we get a fresh debug daemonset.
> Delete 'cnf-suite' namespace

- README.md
- scripts/delete-namespaces.sh
- scripts/download-unstable.sh
Added some updated language and links to the README. 
Added some safeguards in the `scripts` to prevent scripts from running if `docker` or `oc` binaries aren't found for example.
> Update README and scripts

- .github/workflows/pre-main.yml
- .github/workflows/qe-nightly.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1598
> Update Go to v1.21.4

- tests/networking/helper/helper.go
- tests/networking/helper/helper_test.go
Adds some quick unit tests for the networking helper.
> Add networking helper unit tests

- scripts/run-tests.sh
Reverts test-network-function/cnfcert-tests-verification#575
> Revert "Increase flaky retries from 2 to 3"

- scripts/run-tests.sh
Reverts test-network-function/cnfcert-tests-verification#595
> Revert "Reduce the number of procs for parallel"

- tests/platformalteration/tests/platform_alteration_service_mesh.go
https://github.com/istio/istio/releases/tag/1.20.0
> Update istio to v1.20.0

- .github/workflows/pre-main.yml
- .github/workflows/qe.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1697
> Update Go to v1.21.5

- .github/workflows/pre-main.yml
- tests/globalhelper/daemonset.go
- tests/globalhelper/daemonset_test.go
- tests/globalhelper/nodes.go
Follow up to #623 which introduced the check for GetNumberOfNodes().
> Fix daemonset unit tests

- tests/accesscontrol/helper/helper.go
- tests/networking/helper/helper.go
- tests/utils/deployment/deployment.go
- tests/utils/nad/nad.go
- tests/utils/service/service.go
- tests/utils/service/service_test.go
> Adjust redefine funcs to not return their own objects

- tests/globalhelper/clusterrolebindings_test.go
- tests/globalhelper/deployment_test.go
- tests/globalhelper/helper.go
- tests/globalhelper/helper_test.go
- tests/utils/container/container_test.go
- tests/utils/subscription/subscription_test.go
Add some more unit tests in various files that were lacking.
> Add more unit tests

- config/config.yaml
- tests/globalhelper/runhelper.go
- tests/utils/config/config.go
- tests/utils/container/container.go
> Add container engine variable

- .github/workflows/pre-main.yml
- .github/workflows/qe.yml
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1778
> Remove ginkgo_removal refs

- playbooks/inventory.ini
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1776
> Remove runners 2-4

- README.md
> Remove reference to self-hosted QE nightlies

- tests/affiliatedcertification/tests/affiliated_certification_helm_version.go
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1801
> Helm version skipped instead of passed

- .github/workflows/pre-main.yml
- .github/workflows/qe.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1804
> Update Go to v1.21.6

- .github/workflows/qe.yml
Similar to: https://github.com/test-network-function/cnf-certification-test/pull/1821
> Remove free disk space cleanup

- tests/platformalteration/tests/platform_alteration_service_mesh.go
https://github.com/istio/istio/releases/tag/1.20.3
> Update Istio to v1.20.3

- .github/workflows/pre-main.yml
- .github/workflows/qe.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1873
> Update Go to v1.21.7

- tests/accesscontrol/parameters/parameters.go
Testing out making the limits and requests smaller to better fit more resource restricted environments running QE.
> Modify resources requested for access-control

- scripts/golangci-lint.sh
- tests/globalhelper/daemonset_test.go
- tests/utils/client/clients.go
- tests/utils/config/config_test.go
- tests/utils/execute/ginkgo.go
- tests/utils/nodes/nodes.go
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1892
> Update GolangCI-lint to v1.56.2

- .github/workflows/pre-main.yml
- .github/workflows/qe.yml
- .golangci.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1902
> Update Go to v1.22

- tests/operator/tests/operator_install_source.go
- tests/operator/tests/operator_install_status.go
- tests/operator/tests/operator_install_status_no_privileges.go
Switched `Serial` to `Ordered` for operator suite.
Update quay operator to 3.11.
> Operator suite fixes

- .github/workflows/pre-main.yml
- .github/workflows/qe.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1973
> Update Go to v1.22.2

- .github/workflows/pull-images.yml
A simple cron that will pull some images nightly to see if they actually exist.  Edit this list in the future if image are changed/added in QE.
> Add github action cron for pulling images

- scripts/run-tests.sh
Reverts test-network-function/cnfcert-tests-verification#747
> Revert "Temporarily limit procs to 4"

- tests/affiliatedcertification/affiliated_certification_suite_test.go
- tests/operator/operator_suite_test.go
Commenting out these sections as we play around with disconnected registries.
> Temporarily disable catalogsource precheck

- tests/affiliatedcertification/tests/affillated_certification_helm_chart.go
- tests/platformalteration/tests/platform_alteration_service_mesh.go
> Use gcr.io for istio; update version to v1.21.2

- .github/workflows/pre-main.yml
- .github/workflows/qe.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/2053
> Update Go to v1.22.3

- .github/workflows/qe.yml
- tests/observability/tests/crd_status.go
Related to work done: https://github.com/test-network-function/cnf-certification-test/pull/2095
> Build the binary and test against

- tests/affiliatedcertification/parameters/parameters.go
- tests/affiliatedcertification/tests/affiliated_certification_invalid_operator.go
- tests/affiliatedcertification/tests/affiliated_certification_operator.go
> Automatically lookup nginx operator version

- .github/workflows/pre-main.yml
- .github/workflows/qe.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/2134
> Update Go to v1.22.4

- tests/operator/tests/operator_install_source.go
Adding `Serial` back.  Seems to be way more stable.
> Troubleshoot operator suite

- tests/globalhelper/catalogsources.go
> Add 4.16 community operators

- tests/operator/parameters/parameters.go
- tests/operator/tests/operator_crd_openapi_schema.go
- tests/operator/tests/operator_crd_versioning.go
- tests/operator/tests/operator_install_source.go
- tests/operator/tests/operator_install_status.go
- tests/operator/tests/operator_install_status_no_privileges.go
- tests/operator/tests/operator_semantic_versioning.go
Related to a change here: https://github.com/test-network-function/cnf-certification-test/pull/2145
> Add CRD Filters to operator tests

- tests/accesscontrol/parameters/parameters.go
Make these tests request less resources.
> Modify accesscontrol request and limits

- tests/globalhelper/catalogsources.go
Support for the upcoming 4.17 OCP release.
> Add 4.17 community operators support

- .golangci.yml
- scripts/golangci-lint.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/2216
> Update GolangCI-lint to v1.59.1

- .github/workflows/pre-main.yml
- .github/workflows/qe.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/test-network-function/cnf-certification-test/pull/2229
> Update Go to v1.22.5

- tests/globalhelper/init.go
- tests/globalhelper/runhelper.go
Wait for: https://github.com/test-network-function/cnf-certification-test/pull/2299
> Sanitize the claim for collector

- tests/platformalteration/tests/platform_alteration_service_mesh.go
https://github.com/istio/istio/releases/tag/1.22.3
> Update istio to v1.22.3

- tests/affiliatedcertification/parameters/parameters.go
- tests/lifecycle/parameters/parameters.go
- tests/manageability/parameters/parameters.go
- tests/networking/parameters/parameters.go
- tests/networking/tests/networking_default_network.go
- tests/operator/parameters/parameters.go
- tests/performance/parameters/parameters.go
- tests/platformalteration/parameters/parameters.go
> Fix URLs for new repo

- .github/workflows/qe.yml
- README.md
- config/config.yaml
- scripts/download-unstable.sh
Follow up to #867 now that the image jobs have ran correctly overnight.
> Switch the default certsuite image

- scripts/golangci-lint.sh
- tests/globalhelper/helper.go
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2362
> Update GolangCI-lint to v1.60.1

- scripts/golangci-lint.sh
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2372
> Update GolangCI-lint to v1.60.3

- tests/globalhelper/daemonset.go
- tests/globalhelper/daemonset_test.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/daemonset/daemonset.go
- vendor/modules.txt
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite-qe/pull/898
Migrate our `daemonset` package over to the eco-goinfra implementation.
> Migrate daemonset package to eco-goinfra

- .github/workflows/pre-main.yml
- .github/workflows/qe.yml
- .golangci.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2402
> Update Go to v1.23.1

- tests/operator/tests/operator_common.go
- tests/operator/tests/operator_install_source.go
- tests/operator/tests/operator_install_status.go
Also change the `waitUntilOperatorIsReady` func to wait until Succeeded status.
> Remove cloudbees and replace with nginx

- tests/globalhelper/networkpolicy.go
- tests/networking/helper/helper.go
Utilize `networkPolicy` package from eco-goinfra.
> Add networkPolicy pkg from eco-goinfra

- go.mod
- go.sum
- tests/globalhelper/namespaces.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/operatorv1/storagecluster_types.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/schemes/ocs/operatorv1/zz_generated.deepcopy.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/storage/pvc.go
- vendor/modules.txt
Brings in changes from: https://github.com/openshift-kni/eco-goinfra/pull/698
> Update eco-goinfra to latest commit

- tests/globalhelper/resourcequotas.go
https://github.com/openshift-kni/eco-goinfra/pull/701
> Switch Create() for resourceQuotas to eco-goinfra

- .github/workflows/pre-main.yml
- .github/workflows/qe.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2482
> Update Go to v1.23.2

- tests/globalhelper/statefulset.go
- tests/globalhelper/statefulset_test.go
https://github.com/openshift-kni/eco-goinfra/tree/main/pkg/statefulset 
Take advantage of the eco-goinfra statefulset pkg.
> statefulset: migrate to eco-goinfra

- tests/globalhelper/catalogsources.go
- tests/utils/client/clients.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/clusterversion/clusterversion.go
- vendor/github.com/openshift-kni/eco-goinfra/pkg/clusterversion/const.go
- vendor/modules.txt
https://github.com/openshift-kni/eco-goinfra/blob/main/pkg/clusterversion/clusterversion.go
> clusterVersion: migrate to eco-goinfra

- scripts/golangci-lint.sh
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2598
> Update GolangCI-lint to v1.62.2

- tests/globalhelper/catalogsources.go
Add 4.12 and 4.13 community operator indexes.
> Add 4.12 and 4.13 community operators

- scripts/golangci-lint.sh
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2667
> Update GolangCI-lint to v1.63.3

- tests/globalhelper/daemonset.go
- tests/globalhelper/daemonset_test.go
- tests/globalhelper/nodes.go
- tests/observability/tests/container_logging.go
Remove `LabelSelector` from GetNumberOfNodes as well.
> Improve daemonset isReady

- tests/networking/tests/networking_undeclared_container_ports_usage.go
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2685
> Switch undeclared port usage test from Skipped to Passed

- tests/accesscontrol/tests/access_control_pod_host_path.go
- tests/globalhelper/catalogsources.go
- tests/globalhelper/deployment.go
- tests/globalhelper/init.go
- tests/globalhelper/pod.go
- tests/globalhelper/runhelper.go
- tests/operator/parameters/parameters.go
- tests/operator/tests/operator_bundle_image.go
- tests/operator/tests/operator_crd_openapi_schema.go
- tests/operator/tests/operator_crd_versioning.go
- tests/operator/tests/operator_multiple_installed.go
- tests/operator/tests/operator_semantic_versioning.go
- tests/performance/tests/exclusive_cpu_pools.go
- tests/performance/tests/rt_app_no_exec_probes.go
- tests/performance/tests/rt_exclusive_cpu_pool_scheduling_policy.go
- tests/performance/tests/rt_isolated_cpu_pool.go
- tests/performance/tests/shared-cpu-pool-non-rt-scheduling-policy.go
- tests/utils/daemonset/daemonset.go
- tests/utils/daemonset/daemonset_test.go
- tests/utils/deployment/deployment.go
- tests/utils/deployment/deployment_test.go
- tests/utils/replicaset/replicaset.go
- tests/utils/statefulset/statefulset.go
- tests/utils/statefulset/statefulset_test.go
performance: skip if test pod are unschedulable
> Add additional support to performance suite for SNO/CRC

- .github/workflows/pre-main.yml
- .github/workflows/qe.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2704
> Update Go to v1.23.5

- scripts/golangci-lint.sh
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2705
> Update GolangCI-lint to 1.63.4

- .github/workflows/pre-main.yml
- .github/workflows/qe.yml
- go.mod
- scripts/install-latest-go.sh
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2766
> Update Go to v1.23.6

- scripts/golangci-lint.sh
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2792
> Updating GolangCI to v1.64.2

- .github/dependabot.yml
Follow up to: https://github.com/redhat-best-practices-for-k8s/certsuite-qe/pull/1069
> Group actions in dependabot config

- .github/workflows/pre-main.yml
- .golangci.yml
- scripts/golangci-lint.sh
- tests/accesscontrol/tests/access_control_container_host_port.go
- tests/accesscontrol/tests/access_control_nodeport_service.go
- tests/globalhelper/runhelper.go
- tests/utils/daemonset/daemonset_test.go
- tests/utils/deployment/deployment_test.go
- tests/utils/persistentvolume/persistentvolume_test.go
- tests/utils/pod/pod_test.go
- tests/utils/statefulset/statefulset_test.go
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2875
> linter: Update to v2 schema

- go.mod
- go.sum
- scripts/run-tests.sh
- vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
- vendor/github.com/onsi/ginkgo/v2/ginkgo/build/build_command.go
- vendor/github.com/onsi/ginkgo/v2/ginkgo/command/command.go
- vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/compile.go
- vendor/github.com/onsi/ginkgo/v2/ginkgo/run/run_command.go
- vendor/github.com/onsi/ginkgo/v2/ginkgo/watch/watch_command.go
- vendor/github.com/onsi/ginkgo/v2/ginkgo_t_dsl.go
- vendor/github.com/onsi/ginkgo/v2/types/config.go
- vendor/github.com/onsi/ginkgo/v2/types/errors.go
- vendor/github.com/onsi/ginkgo/v2/types/version.go
- vendor/modules.txt
I had to open up an issue with ginkgo to debug, but it helped me figure out what was wrong.
https://github.com/onsi/ginkgo/issues/1539
The problem seems to be that there are spaces in the `$command` and the ginkgo command doesn't appreciate them 😄
> Fix ginkgo command

- .github/workflows/pre-main.yml
- .github/workflows/pull-images.yml
- .github/workflows/qe.yml
- .github/workflows/scorecard.yml
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2927
> Runner update to ubuntu-24.04

- go.mod
- go.sum
- vendor/modules.txt
https://github.com/operator-framework/operator-lifecycle-manager/releases/tag/v0.32.0
> Update OLM to v0.32.0

- .github/workflows/qe-ocp.yml
- .github/workflows/qe.yml
- .golangci.yml
Address the linter failure (missing a new line) and also address the warnings.
> Linter fix

- tests/globalhelper/runhelper.go
We are seeing randomly that tests (even though they are passing are performing very slowly):
```
Networking custom namespace, custom deployment, 3 custom pods on Default network networking-icmpv4-connectivity fail when one pod is disconnected [negative]
/home/labuser2/actions-runner/_work/certsuite/certsuite/certsuite-qe/tests/networking/tests/networking_default_network.go:94
Timeline >>
> Enter [BeforeEach] Networking custom namespace, custom deployment, @ 07/31/25 07:11:22.515
STEP: Create networking-tests-uwsbfbpcvo namespace @ 07/31/25 07:11:22.515
STEP: Generate directories @ 07/31/25 07:11:22.563
STEP: Define certsuite config file @ 07/31/25 07:11:22.563
< Exit [BeforeEach] Networking custom namespace, custom deployment, @ 07/31/25 07:11:22.563 (48ms)
> Enter [It] 3 custom pods on …
```
> Add timeout for LaunchTests

- tests/globalhelper/runhelper.go
#1166 had changes that made the `exec` commands retry the docker/podman commands during image runs but the underlying containers kept running and left a ton of leftovers.
I'm reverting the changes to the image runs while keeping the logic for binary runs.
> Remove retry and context changes for image runs

- go.mod
- tests/performance/helper/helper.go
- tests/performance/performance_suite_test.go
Remove `logrus` as a dependency.
Related to #1215
> Replace logrus with klog/v2
