scripts/golangci-lint.sh
tests/utils/config/config.go

https://github.com/golangci/golangci-lint/releases/tag/v1.44.0
```
INFO [runner] linters took 10.659234125s with stages: goanalysis_metalinter: 10.652175941s 
tests/utils/config/config.go:41:6: variable name 'c' is too short for the scope of its usage (varnamelen)
var c Config
```

Bump GolangCI-lint to v1.44.0

---

.github/workflows/makefile.yml

Go 1.17.6 is now available.
https://twitter.com/golang/status/1479199301352013829
From their release page:
```
go1.17.6 (released 2022-01-06) includes fixes to the compiler, linker, runtime, and the crypto/x509, net/http, and reflect packages. See the Go 1.17.6 milestone on our issue tracker for details.
```

Update Go to 1.17.6

---

scripts/golangci-lint.sh

https://github.com/golangci/golangci-lint/releases/tag/v1.44.1
No code changes found/needed.

Bump GolangCI-lint to v1.44.1

---

tests/affiliatedcertification/affiliatedcertparameters/parameters.go
tests/affiliatedcertification/tests/affiliated_certification_operator.go

Updated case where there are no operators to be certified and removed outdated skip cases that are no longer relevant.

Operator cert skip cases

---

scripts/golangci-lint.sh

https://github.com/golangci/golangci-lint/releases/tag/v1.45.2
Similar to:
https://github.com/test-network-function/cnf-certification-test/pull/92
https://github.com/test-network-function/test-network-function/pull/660
https://github.com/test-network-function/test-network-function-claim/pull/41

Update GolangCI to 1.45.2

---

tests/lifecycle/tests/lifecycle_pod_scheduling.go
tests/utils/deployment/deployment.go

This PR contains 5 lifecycle-pod-scheduling test cases (48120, 48458, 48470, 48471, 48472).

Automate lifecycle-pod-scheduling tests

---

tests/lifecycle/lifehelper/lifehelper.go
tests/lifecycle/tests/lifecycle_deployment_scaling.go
tests/lifecycle/tests/lifecycle_image_pull_policy.go
tests/lifecycle/tests/lifecycle_liveness.go
tests/lifecycle/tests/lifecycle_pod_high_availability.go
tests/lifecycle/tests/lifecycle_pod_owner_type.go
tests/lifecycle/tests/lifecycle_pod_recreation.go
tests/lifecycle/tests/lifecycle_pod_scheduling.go
tests/lifecycle/tests/lifecycle_readiness.go
tests/lifecycle/tests/lifecycle_shutdown.go
tests/utils/deployment/deployment.go

This PR contains the following fixes: 
1. Fix container appending on lifehelper/DefineDeployment
2. Fix number 1 ^^ influenced almost all of the suite, but now it's more accurate and has better readability.
3. pod-scheduling -  daemonSet test is not relevant, since a daemonSet by nature has podAffinity spec, edited it to be relevant.
4. pod-scheduling - same has 3, but on a negative tc.
5. container-shutdown - Fixed RedefineAllContainersWithPreStopSpec, returned from the function before it iterated on all the containers.
This PR was tested 48/48 passed.

Fix several lifecycle issues

---

tests/affiliatedcertification/affiliatedcertparameters/parameters.go

On some CI runs, the k10-kasten operator successfully installs after the timeout of the Eventually() checking for it.

Change timeout param from 5 to 10 minutes

---

tests/lifecycle/tests/lifecycle_container_shutdown.go

The xml report was generated with a wrong tc description because of the " ' ", thus I had to change the
test name.

Fix container shutdown file name, fix It block description to match polarion, change tc polarion number

---

.github/workflows/makefile.yml

https://github.com/actions/setup-go/releases/tag/v3.0.0
v3 is the latest available release of `setup-go`.
Similar to: https://github.com/test-network-function/cnf-certification-test/pull/205

Upgrade to v3 setup-go action

---

.github/workflows/makefile.yml

Similar to: https://github.com/test-network-function/cnf-certification-test/pull/204 
https://github.com/actions/checkout/releases/tag/v3.0.2
`checkout` v3 is the latest available.

Upgrade to v3 checkout action

---

scripts/golangci-lint.sh

https://github.com/golangci/golangci-lint/releases/tag/v1.47.1
Related to: 
- https://github.com/test-network-function/cnf-certification-test/pull/358
- https://github.com/test-network-function/l2discovery/pull/10

Upgrade GolangCI-lint to v1.47.1

---

tests/accesscontrol/tests/access_control_namespace.go

This will fix a failure caused by pods leftover from other tests in the access-control suite.

Added namespace clean to BeforeAll in access-control-namespace

---

tests/accesscontrol/helper/helper.go
tests/accesscontrol/parameters/parameters.go
tests/accesscontrol/tests/access_control_pod_automount_service_account_token.go
tests/utils/deployment/deployment.go

Remaining four access-control pod-automount-service-account-token test cases

Access control automount token service account tests

---

scripts/golangci-lint.sh

Related to: https://github.com/test-network-function/cnf-certification-test/pull/456
https://github.com/golangci/golangci-lint/releases/tag/v1.49.0

Upgrade GolangCI-lint to v1.49.0

---

tests/platformalteration/helper/helper.go
tests/platformalteration/parameters/parameters.go
tests/platformalteration/tests/platform_alteration_sysctl_config.go

Automated  51302 +  51332.
The negative scenario (51333) is still under investigation, currently having issues creating a file in
/etc/sysctl.d/... that contains a key-value pair.

Add 2 sysctl_config tests

---

tests/accesscontrol/tests/access_control_pod_host_ipc.go
tests/accesscontrol/tests/access_control_pod_host_network.go
tests/accesscontrol/tests/access_control_pod_host_pid.go
tests/utils/deployment/deployment.go

Based on mostly process of elimination, I think this *might* fix the access-control tests that fail due to deployment creation timeout. If we merge it in and it doesn't fix those tests during the Jenkins build, I'll revert it.

Changed deployment spec-changing funcs that don't use pointers for values to return deployment pointer

---

.github/workflows/makefile.yml

https://groups.google.com/g/golang-announce/c/x49AQzIVX-s
Similar changes:
- https://github.com/test-network-function/cnf-certification-test/pull/492
- https://github.com/test-network-function/test-network-function-claim/pull/62
- https://github.com/test-network-function/l2discovery/pull/15
- https://github.com/test-network-function/privileged-daemonset/pull/7
- https://github.com/test-network-function/oct/pull/1

Update Go to 1.18.6

---

.github/workflows/makefile.yml

https://groups.google.com/g/golang-announce/c/xtuG5faxtaU
Security: Includes security fixes for archive/tar (CVE-2022-2879), net/http (CVE-2022-2880), and regexp (CVE-2022-41715).
Related to: https://github.com/test-network-function/cnf-certification-test/pull/571

Update Go to v1.19.2

---

.github/dependabot.yml

Similar changes/files: 
- https://github.com/test-network-function/cnf-certification-test/blob/main/.github/dependabot.yml
- https://github.com/test-network-function/autodiscover/pull/2
- https://github.com/test-network-function/l2discovery/pull/9
- https://github.com/test-network-function/oct/pull/4
Still maintains the `vendor` directory.

Add dependabot YAML

---

scripts/install-latest-go.sh

The current go version being installed by CI executer bm-setup playbook is go1.18. our project requires go1.19
I Implemented the latest go version installation In order to avoid errors like in the following job: 
https://auto-jenkins-csb-kniqe.apps.ocp-c1.prod.psi.redhat.com/view/TNF/job/CNF/job/test-ocp-general-tnf/435/console
`go: go.mod file indicates go 1.19, but maximum version supported by tidy is 1.18`

add latest go version installation

---

scripts/golangci-lint.sh

https://github.com/golangci/golangci-lint/releases/tag/v1.50.0
Related to: https://github.com/test-network-function/cnf-certification-test/pull/604

Upgrade Golangci-lint to v1.50.0

---

tests/globalhelper/pod.go
tests/globalhelper/runhelper.go
tests/lifecycle/parameters/parameters.go
tests/lifecycle/tests/lifecycle_affinity_required_pods.go
tests/utils/pod/pod.go

Considering this [PR](https://github.com/test-network-function/cnf-certification-test/pull/608/files)
affinity-required-deployments/statefulSets will not be automated.
I had to edit the runhelper.go in order to be able to provide 1 out of 3 labels each tc must have: 
1. test case name
2. common/ extended tags
3. test suite name
thus, I added the -l argument in the cmd line, which will target the specific tc, instead of specifying if it's common/extended.
Eventually, using -l made the -f redundant, and hence I deleted it.

Automated affinity required pods tc verification

---

tests/platformalteration/parameters/parameters.go
tests/platformalteration/tests/platform_alteration_hugepages_2m.go
tests/utils/deployment/deployment.go
tests/utils/pod/pod.go

* There is an ongoing [PR](https://gitlab.cee.redhat.com/cnf/cnf-pipeline/-/merge_requests/420) in cnf-pipeline repo to configure hugepages-2m in the performance profile 
being applied in the CI. 
Automated 55865-55868.

Added platform-alteration-hugepages-2m-only verification scenarious

---

tests/lifecycle/tests/lifecycle_affinity_required_pods.go

this is for debugging purposes, the affinity-required label is left on the pods even after the affinity-required pod tc is finished. 
this will be reverted once the issue is solved.

Disabled affinity req pods tc for debugging purposes

---

tests/globalhelper/pod.go

This is required because the current implementation is changing the original labels.

Roll back to prior implementation of AppendLabelsToPod function

---

tests/platformalteration/parameters/parameters.go
tests/platformalteration/tests/platform_alteration_ocp_node_os.go

Same as ocp-lifecycle tc, there is no way to change the environment, just expect it to pass.

Add ocp-node-os tc

---

README.md
scripts/run-tests.sh

ginkgo seed is used to rerun the same exact job with a seed that was generated by ginkgo, which will improve debugging.

Add ginkgo seed usage to improve debugging

---

.github/workflows/makefile.yml

https://groups.google.com/g/golang-announce/c/wrmRT7JlevE
Related to: https://github.com/test-network-function/cnf-certification-test/pull/779

Update Go to v1.19.5

---

.github/workflows/makefile.yml

Related to: https://github.com/test-network-function/cnf-certification-test/pull/864
https://groups.google.com/g/golang-announce/c/V0aBFqaFs_E

Update Go to 1.19.6

---

go.mod
tests/globalhelper/helper.go
tests/utils/config/config.go

Related to: https://github.com/test-network-function/cnf-certification-test/pull/857
The v2 library had a vulnerability that was corrected in v3.

Upgrade yaml library to v3

---

.github/workflows/makefile.yml
.golangci.yml
go.mod

Release Notes: https://tip.golang.org/doc/go1.20
Related to: https://github.com/test-network-function/cnf-certification-test/pull/873

Upgrade Go to v1.20.1

---

tests/platformalteration/parameters/parameters.go

https://quay.io/repository/jitesoft/nginx/manifest/sha256:8876307eb58f5c35b4c78c6979ae5ed36bc3bae33c82a1d5e7572fe62fa3cbc7
This is the link to the `1.23.3` release of this nginx image.
The reason for this change is from the logs of the QE runs:
```
[37mDEBUG  [0m[Mar 10 22:20:38.628][suite.go: 79] Running preflight container tests for: test  
[36mINFO   [0m[Mar 10 22:20:38.628][containers.go: 78] Running preflight container test against image: quay.io/baselibrary/ubuntu:latest with name: test 
[31mERROR  [0m[Mar 10 22:20:40.471][containers.go: 115] failed to pull remote container: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377 
[31mFATAL  [0m[Mar 10 22:20:40.471][suite.go: 82] failed …
```

Update NotRedHatRelease image ref

---

tests/utils/daemonset/daemonset.go
tests/utils/deployment/deployment.go

PR#229 mistakenly modified the CNCF annotations that are used to set the extra multus networks for pods under test.

Fixed CNCF annotation for multus networking test cases.

---

.github/workflows/makefile.yml

Related to: https://github.com/test-network-function/cnf-certification-test/pull/927

Update setup-go action to v4

---

tests/platformalteration/helper/helper.go
tests/platformalteration/tests/platform_alteration_is_redhat_release.go

The negative TCs for this TNF test case failed because both deployment and statefulset couldn't be created and the QE tc timed-out.
It happened because the selected non-UBI image for this TC doesn't have a /bin/bash binary. The shell is linked to busybox in /bin/sh instead.

Fixed negative test cases for platform-lateration-is-redhat-release.

---

.github/dependabot.yml

Related to: https://github.com/test-network-function/cnf-certification-test/pull/954

Add dependabot config for github actions

---

tests/affiliatedcertification/parameters/parameters.go
tests/affiliatedcertification/tests/affiliated_certification_operator.go

replaced infinibox operator with prometurbo, which should pass on all ocp versions

Replaced infinibox operator with prometurbo

---

tests/networking/parameters/parameters.go

See (https://github.com/test-network-function/cnf-certification-test/pull/1120)

Changing networking-service-type test name to access-control-service-type

---

scripts/golangci-lint.sh

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1236
https://github.com/golangci/golangci-lint/releases/tag/v1.53.3

Update GolangCI-lint to v1.53.3

---

tests/accesscontrol/parameters/parameters.go
tests/accesscontrol/tests/access_control_pod_cluster_role_bindings.go
tests/globalhelper/helper.go
tests/utils/rbac/rbac.go

* Changed "my-role-binding" to "my-cluster-role-binding"
* Added safeguard `Get` calls before running Create or Delete commands.
* Corrected some typos.

Cleanup 'my-role-binding' in accesscontrol suite tests

---

Makefile
scripts/download-unstable.sh

Checks for an existing `unstable` image.  If it exists, delete it and re-pull the image for use.

Download new unstable image

---

README.md
scripts/download-unstable.sh

If `FORCE_DOWNLOAD_UNSTABLE` is unset, the script is skipped.

Add check for FORCE_DOWNLOAD_UNSTABLE in download-unstable.sh script

---

playbooks/fedora-setup.yml

Adds an ansible playbook for bootstraping fedora servers in our lab for running QE.
Note: I am not checking in the inventory file that I'm using for security concerns.

Add ansible playbooks for managing QE self-hosted runners

---

tests/globalhelper/nodes.go

Instead of using `OcpClientInterface` to modify schedulers (OCP only), switch the `EnableMasterScheduling` function to use the k8s client and modify the node objects to remove the taint that is preventing scheduling in the first place.
Getting rid of the `OcpClientInterface` makes the QE code more compatible with running against plain k8s.

Modify EnableMasterScheduling

---

tests/globalhelper/runtimeclass.go

Issuing the `Create()` without checking first if runtimeClass exists ends in an error if it has already been created.

Check for existing runtime class to avoid error

---

tests/globalhelper/runtimeclass.go

Removing changes from #397 
The `Get` was issuing a failure which was causing fresh runs to fail:

Revert changes for runtimeClass Create()

---

tests/lifecycle/helper/helper.go
tests/lifecycle/tests/lifecycle_storage_required_pods.go

Add a cleanup in the `AfterEach` section of these tests to cleanup the `local-storage` storageclass.

Cleanup 'local-storage' storageclass

---

tests/accesscontrol/tests/access_control_security_context.go
tests/utils/namespaces/namespaces.go

Adds checks to namespace cleanup logic.  
* Makes sure that a namespace exists before performing the `Clean()` operation.
* Edits `DeleteAndWait` function to handle IsNotFound errors.

Add checks in namespace cleanup

---

tests/globalhelper/nodes.go
tests/networking/helper/helper.go
tests/networking/tests/networking_default_network.go
tests/networking/tests/networking_dual_stack_service.go
tests/networking/tests/networking_multus_links.go
tests/networking/tests/networking_ocp_reserved_ports_usage.go
tests/networking/tests/networking_reserved_partner_ports.go

Changes:
- Add safeguard into `addControlPlaneTaint` to check for existing taints to avoid error.
- Changes to `removeControlPlaneTaint` to modify the existing object to avoid error.
- Add `IsAlreadyExists` checks to `DefineAndCreateServiceOnCluster` function.
- Add `IsAlreadyExists` checks to `DefineAndCreateNadOnCluster` function.
- Add `EnsureAllNodesAreLabeled` to `tests/networking/tests/networking_default_network.go` tests.
- Added `RedefineServiceToHeadless` function to designate a headless service (no ClusterIP designation).

Fixes for networking tests

---

tests/globalhelper/helper.go
tests/globalparameters/globalparameters.go

Updated field names to match this change: https://github.com/test-network-function/cnf-certification-test/pull/1313
We might also want to update the example tnf_config.yml here: https://github.com/test-network-function/cnf-certification-test/blob/main/cnf-certification-test/tnf_config.yml

updated container certification config field names

---

tests/accesscontrol/access_control_suite_test.go
tests/accesscontrol/helper/helper.go
tests/accesscontrol/helper/helper_test.go
tests/accesscontrol/tests/access_control_pod_cluster_role_bindings.go
tests/affiliatedcertification/affiliated_certification_suite_test.go
tests/affiliatedcertification/tests/affillated_certification_helm_chart.go
tests/globalhelper/init.go
tests/lifecycle/lifecycle_suite_test.go
tests/manageability/manageability_suite_test.go
tests/networking/networking_suite_test.go
tests/observability/observability_suite_test.go
tests/operator/operator_suite_test.go
tests/performance/performance_suite_test.go
tests/platformalteration/platform_alteration_suite_test.go
tests/utils/deployment/deployment.go
tests/utils/namespaces/namespaces.go

Adds unit tests to all of the access-control suite of helper functions.  One of the things I'm noticing is that we pass around the entire `clientset` struct when we only need certain interfaces which makes it harder to spoof/test certain functions.
I also added a func to completely override the `apiclient` that we return from `globalhelper.GetAPIClient` to return a client that's pre-loaded with the `fake` k8s client.
See `UnsetTestK8sAPIClient` and `SetTestK8sAPIClient` funcs.
Notable changes:
- `DefineDeploymentWithClusterRoleBindingWithServiceAccount` had its call to create a cluster role binding moved outside of the func.

Add access-control helper unit tests

---

tests/accesscontrol/tests/access_control_pod_role_bindings.go

Follow up to: https://github.com/test-network-function/cnf-certification-test/pull/1210 
Having the default service account is considered a failure now per the above PR.

Switch accesscontrol test case to negative for default SA

---

.github/workflows/makefile.yml
.golangci.yml
scripts/install-latest-go.sh

https://go.dev/doc/go1.21
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1344

Update Go to v1.21.0

---

tests/observability/helper/helper.go

Add an `IsAlreadyExists` error check on this function.

Fix CRD Create

---

tests/globalhelper/runhelper.go

Utilizes the environment variable `TNF_OMIT_ARTIFACTS_ZIP_FILE` to prevent the test suite from creating a zip file when all we do is delete the reports directory anyways.

Omit zip file creation in QE

---

tests/manageability/manageability_suite_test.go

`TestPerformance` --> `TestManageability`
This looks to have been a copy paste error.

Adjust func name for manageability

---

tests/lifecycle/tests/lifecycle_persistent_volume_reclaim_policy.go
tests/lifecycle/tests/lifecycle_storage_required_pods.go
tests/utils/persistentvolume/persistentvolume.go

The `namespace` variable was unused and doesn't make sense here anyways because PersistentVolumes are not namespaced resources.

Remove 'namespace' from DefinePersistentVolume()

---

tests/lifecycle/tests/lifecycle_persistent_volume_reclaim_policy.go
tests/lifecycle/tests/lifecycle_storage_required_pods.go

For example, if you use `DefinePersistentVolume` and it hands you a PV object, we should use the object's `Name` field rather than the global variable parameter incase something happens (in a future PR 😉 ) to the objects themselves.

Use object references instead of global variables

---

scripts/run-tests.sh
tests/globalhelper/helper.go
tests/globalhelper/init.go
tests/globalhelper/runhelper.go
tests/manageability/manageability_suite_test.go
tests/manageability/tests/container_port_name_format.go
tests/manageability/tests/containers_image_tag.go

Enables parallel runs in the `manageability` suite.
- Builds on #444 and removes the `Serial` label from these tests.
- Similar to the changes learned in #445.

Enable parallel manageability suite

---

tests/networking/helper/helper.go
tests/networking/networking_suite_test.go
tests/networking/tests/networking_default_network.go
tests/networking/tests/networking_dual_stack_service.go
tests/networking/tests/networking_multus_links.go
tests/networking/tests/networking_network_policy_deny_all.go
tests/networking/tests/networking_ocp_reserved_ports_usage.go
tests/networking/tests/networking_reserved_partner_ports.go
tests/networking/tests/networking_undeclared_container_ports_usage.go

Enables parallel runs in the `networking` suite!  🎉   This brings the amount of time to run the networking suite down from 30 minutes to ~80 seconds.  🤯 
Notable changes for reviewers:
- Added a function in the `globalhelper` package named `GenerateRandomString` which helps randomize the namespaces in which the resources are deployed into.
- Added the `-p` to the calls to ginkgo in `scripts/run-tests.sh`.  This enables the parallel running.  Follow-up to #444.
- Added `OverrideReportDir` and `OverrideTnfConfigDir` funcs for overriding the default directories on the machine running the QE tests.
- Moved the `"Ensure all nodes are labeled with 'worker-cnf' label"` step to the `BeforeSuite` block for organization.

Enable parallel networking suite

---

README.md
scripts/run-tests.sh

Adds an environment variable that turns on parallel flag in ginkgo if its set to true.
`ENABLE_PARALLEL=true` to turn it on.
Follow up to #458 where some suites are not acting correctly when parallel is enabled by default.

Add ENABLE_PARALLEL env var

---

README.md

The README.md was missing the manageability suite.

Add 'manageability' to the list of suites

---

tests/globalhelper/init.go
tests/globalhelper/reporthelper.go
tests/lifecycle/tests/lifecycle_affinity_required_pods.go

Adds the `By("Remove reports from report directory")` back to the `AfterEachCleanupWithRandomNamespace` func.
I accidentally removed this step.

Remove report dir after runs

---

tests/lifecycle/tests/lifecycle_crd_scaling.go

Since the QE repo is not installing the `crd-operator-scaling` resources first as part of the code, we should properly skip the test since there is nothing to test against.
I added a comment to add the operator install.

Skip if crd-operator-scaling is not found

---

tests/lifecycle/tests/lifecycle_crd_scaling.go

I think this was mistaken for the `crd-operator-scaling` repo which is not what this test is targeting.  I updated the comments to point at `cr-operator-scaling` and moved the logic to check for the operator into the It() block.

Use 'cr' instead of 'crd'

---

tests/accesscontrol/tests/access_control_nodeport_service.go

This is already taken care of in access_control_suite_test and was causing issues when running the nodeport testcases.

removed report cleanup from BeforeEach and AfterEach of nodeport service tests

---

tests/accesscontrol/access_control_suite_test.go
tests/accesscontrol/helper/helper.go
tests/accesscontrol/helper/helper_test.go
tests/accesscontrol/tests/access_control_bpf_capability_check.go
tests/accesscontrol/tests/access_control_container_host_port.go
tests/accesscontrol/tests/access_control_container_non-root_user.go
tests/accesscontrol/tests/access_control_ipc_lock_capability_check.go
tests/accesscontrol/tests/access_control_namespace.go
tests/accesscontrol/tests/access_control_namespace_resource_quota.go
tests/accesscontrol/tests/access_control_net_admin_capability_check.go
tests/accesscontrol/tests/access_control_net_raw_capability_check.go
tests/accesscontrol/tests/access_control_no_1337_uid.go
tests/accesscontrol/tests/access_control_nodeport_service.go
tests/accesscontrol/tests/access_control_one_process_per_container.go
tests/accesscontrol/tests/access_control_pod_automount_service_account_token.go
tests/accesscontrol/tests/access_control_pod_cluster_role_bindings.go
tests/accesscontrol/tests/access_control_pod_host_ipc.go
tests/accesscontrol/tests/access_control_pod_host_network.go
tests/accesscontrol/tests/access_control_pod_host_path.go
tests/accesscontrol/tests/access_control_pod_host_pid.go
tests/accesscontrol/tests/access_control_pod_role_bindings.go
tests/accesscontrol/tests/access_control_pod_service_account.go
tests/accesscontrol/tests/access_control_projected_volume_service_account_token.go
tests/accesscontrol/tests/access_control_requests_and_limits.go
tests/accesscontrol/tests/access_control_security_context.go
tests/accesscontrol/tests/access_control_security_context_privilege_escalation.go
tests/accesscontrol/tests/access_control_ssh_daemons.go
tests/accesscontrol/tests/access_control_sys_admin_capability_check.go
tests/accesscontrol/tests/access_control_sys_ptrace.go
tests/globalhelper/init.go

Enables the access-control suite to run in parallel 🥳 
* The two skipped tests are planned because we skip tests requiring SELinux.  See #438 
Notable changes for reviewers:
- Added `k8s.IsAlreadyExists` checks to installplan and subscription Create() funcs.
- Had to change some of the ports to not overlap for the NodePort tests.
- Left the `Serial` flag on the access-control-namespace set of tests because it tests the entire cluster's worth of namespaces for each test so there is overlap.  Unavoidable.

Enable parallel access-control suite

---

tests/networking/tests/networking_network_policy_deny_all.go

Use ginkgo's `DeferCleanup` to clean these namespaces up incase of failure.

Use DeferCleanup() in networking suite

---

tests/observability/parameters/parameters.go
tests/observability/tests/pod_disruption_budget.go

The new scenarios covered are:
* The PDB matchLabels field does not match the workload label
* There is no PDB defined

observability: add two more cases to pod-disruption-budget

---

tests/globalhelper/daemonset.go
tests/globalhelper/deployment.go
tests/globalhelper/statefulset.go
tests/utils/daemonset/daemonset.go
tests/utils/deployment/deployment.go
tests/utils/replicaset/replicaset.go

In the `globalhelper` package, we have a bunch of these funcs that `CreateAndWait...` and for the most part I think they do their job waiting for the number of Running replicas to be "up" but I don't think the resources are truly up and running before the tests are kicked off which is generally right after we create the resources.
Adding these sleeps seems to fix the instability I've been seeing in my test runs:
https://github.com/test-network-function/cnf-certification-test/actions/runs/6053059734?pr=1377 (for example)
EDIT:
I have taken @jmontesi's advice and switched to `minReadySeconds: 30` for deployments, daemonsets, and replicasets.  This seems to have cleared up the random failures I have been seeing in my testing.  I also changed the conditional statements for how to determine if …

Add minReadySeconds to specs

---

README.md
tests/affiliatedcertification/affiliated_certification_suite_test.go
tests/affiliatedcertification/helper/helper.go
tests/affiliatedcertification/tests/affiliated_certification_container.go
tests/affiliatedcertification/tests/affiliated_certification_container_is_certified_digest.go
tests/affiliatedcertification/tests/affiliated_certification_invalid_operator.go
tests/affiliatedcertification/tests/affiliated_certification_operator.go
tests/affiliatedcertification/tests/affiliated_common.go
tests/affiliatedcertification/tests/affillated_certification_helm_chart.go

There are a lot of tests in the affiliated-certification suite that rely on running on OCP and having operator hub available.  Also because of the OCP requirement there are pull secrets that are available in OCP vs normal kubernetes so I'm avoiding tests that have to pull certified images from `registry.connect.redhat.com`.
Tests that won't run properly in Kind:
* affiliated-certification-container-is-certified-digest
* affiliated-certification-operator-is-certified
These have been added to the README list of tests that get skipped in Kind.

Enable affiliated-certification in parallel

---

tests/globalhelper/daemonset.go
tests/globalhelper/deployment.go
tests/globalhelper/replicaset.go
tests/globalhelper/reporthelper.go

Switching the logic to look at the NumberAvailable.
NumberReady doesn't wait for the `minReadySeconds` added in #475 
https://docs.okd.io/latest/rest_api/workloads_apis/daemonset-apps-v1.html#status
`The number of nodes that should be running the daemon pod and have one or more of the daemon pod running and available (ready for at least spec.minReadySeconds)`

Switch to NumberAvailable

---

tests/affiliatedcertification/tests/affiliated_certification_operator.go
tests/affiliatedcertification/tests/affillated_certification_helm_chart.go

-We no longer need to remove labels after each operator certification test case since the random namespace is removed each time.
-The helm chart certification tests were still trying to use the non-random namespace they used previously.

Affiliated certification test fixes

---

tests/operator/operator_suite_test.go

Adding a check for Kind clusters in the `operator` suite of tests to disable them if ran on Kind.

Skip operator tests if Kind cluster

---

.gitignore
Makefile

Similar to: https://github.com/test-network-function/cnf-certification-test/pull/49 
Creates a coverage report for unit tests.

Add 'make coverage-html' path

---

tests/platformalteration/tests/platform_alteration_base_image.go
tests/platformalteration/tests/platform_alteration_hugepages_config.go
tests/platformalteration/tests/platform_alteration_is_selinux_enforcing.go
tests/platformalteration/tests/platform_alteration_sysctl_config.go

We expect the `List` of items to not be empty so I put some `Expect` commands to prevent panics in these situations.

Add slice safeguards

---

tests/globalhelper/daemonset.go
tests/globalhelper/daemonset_test.go
tests/lifecycle/tests/lifecycle_container_startup.go
tests/lifecycle/tests/lifecycle_cpu_isolation.go
tests/lifecycle/tests/lifecycle_image_pull_policy.go
tests/lifecycle/tests/lifecycle_liveness.go
tests/lifecycle/tests/lifecycle_pod_scheduling.go
tests/lifecycle/tests/lifecycle_readiness.go
tests/lifecycle/tests/lifecycle_startup_probe.go
tests/networking/helper/helper.go
tests/networking/tests/networking_default_network.go
tests/observability/tests/container_logging.go
tests/observability/tests/termination_policy.go
tests/platformalteration/tests/platform_alteration_base_image.go
tests/platformalteration/tests/platform_alteration_boot_params.go
tests/platformalteration/tests/platform_alteration_hugepages_config.go
tests/platformalteration/tests/platform_alteration_is_redhat_release.go
tests/platformalteration/tests/platform_alteration_is_selinux_enforcing.go
tests/platformalteration/tests/platform_alteration_sysctl_config.go
tests/platformalteration/tests/platform_alteration_tainted_node_kernel.go

Similar to #426 where I added some unit tests for the accesscontrol helper funcs.
I changed the function definition for the `CreateAndWaitUntilDaemonSetIsReady` function to accept an interface to be able to unit test these funcs in an isolated environment.
Eventually the goal would be to migrate all of the helper funcs to have some level of unit testing so we're able to determine if code is doing what it is supposed to be doing.

Add daemonset unit tests

---

tests/operator/operator_suite_test.go

Follow up to: https://github.com/test-network-function/cnfcert-tests-verification/pull/485
Skip the cleanup if this is Kind cluster as well.

Skip operator tests cleanup

---

tests/affiliatedcertification/tests/affiliated_certification_invalid_operator.go

Skip the `AfterEach` since we're already skipping this whole section in `BeforeAll`.

Fix affiliated-certification

---

tests/affiliatedcertification/tests/affiliated_certification_container.go
tests/observability/tests/container_logging.go

Follow up to: https://github.com/test-network-function/cnf-certification-test/pull/1439
These changes were introduced in the test suite that change the expected outcome of these test scenarios.
Bonus: Added more `By()` logs in two observability suite tests.

Fix affiliated-certification suite to expect different results

---

scripts/delete-namespaces.sh
tests/accesscontrol/tests/access_control_crd_roles.go
tests/accesscontrol/tests/access_control_pod_cluster_role_bindings.go
tests/globalhelper/rbac.go
tests/lifecycle/tests/lifecycle_cpu_isolation.go
tests/performance/tests/exclusive_cpu_pools.go
tests/platformalteration/tests/platform_alteration_tainted_node_kernel.go
tests/utils/daemonset/daemonset.go
tests/utils/statefulset/statefulset.go

Found a couple of places where I missed adding `MinReadySeconds` and `TerminationGracePeriodSeconds` in both the daemonset code and the statefulset code.
Additional changes:
- Created a script to cleanup namespaces that may or may not be leftover from prior runs.
- Added some `DeferCleanup` functions to cleanup leftover `Role` objects.

Debug daemonsets

---

tests/globalhelper/runtimeclass.go
tests/lifecycle/tests/lifecycle_cpu_isolation.go
tests/lifecycle/tests/lifecycle_persistent_volume_reclaim_policy.go
tests/lifecycle/tests/lifecycle_storage_required_pods.go
tests/performance/helper/helper.go
tests/performance/parameters/parameters.go
tests/performance/tests/exclusive_cpu_pools.go
tests/performance/tests/rt_isolated_cpu_pool.go
tests/utils/persistentvolume/persistentvolume.go

Switch `lifecycle-cpu-isolation` tests to use the `Serial` ginkgo decorator as I have seen differences during parallel runs on systems with a lot of CPUs (QE runners have 16 cores) and the free tier Github Ubuntu runners which have 2 cores.  
Bonus changes:
- Utilize `DeferCleanup` instead of appending to a slice for the names of the RTC's created during tests.
- Set a `ClaimRef` in the `PersistentVolume` objects we are creating so they are explicitly bound to certain PVCs.
- Put some NumCPU safeguards in the CPU isolation tests to make sure we have at least > 2 CPUs available on the Kind machines.

Add 'Serial' decorator for cpu-isolation tests

---

tests/accesscontrol/tests/access_control_pod_role_bindings.go

If these tests panic they may leave leftover namespaces by accident.

Add some DeferCleanup() calls after namespace creation

---

tests/accesscontrol/tests/access_control_crd_roles.go
tests/accesscontrol/tests/access_control_pod_automount_service_account_token.go
tests/accesscontrol/tests/access_control_pod_cluster_role_bindings.go
tests/accesscontrol/tests/access_control_pod_role_bindings.go
tests/accesscontrol/tests/access_control_pod_service_account.go
tests/globalhelper/clusterrolebindings.go
tests/globalhelper/clusterrolebindings_test.go
tests/globalhelper/helper.go
tests/globalhelper/rbac.go
tests/globalhelper/rbac_test.go
tests/utils/rbac/rbac.go

Notable changes: 
- Moved `Create` and `Delete` Cluster Role Binding funcs from helper.go to their own file.
- Cherry picked the changes from #513 into this branch.
- Removed references to `Namespace` fields in cluster role binding objects.

Create unit tests for cluster role bindings and others

---

tests/observability/tests/container_logging.go

The inconsistencies in the `observability` QE test runs has me excluding these two additional tests from running.

Exclude 2 additional observability tests from Kind clusters

---

tests/accesscontrol/tests/access_control_pod_cluster_role_bindings.go

The name of the service account and the namespace were out of order.

Fix order of parameters

---

tests/accesscontrol/tests/access_control_crd_roles.go
tests/lifecycle/helper/helper.go
tests/lifecycle/lifecycle_suite_test.go
tests/lifecycle/tests/lifecycle_crd_scaling.go
tests/lifecycle/tests/lifecycle_pod_high_availability.go
tests/lifecycle/tests/lifecycle_pod_recreation.go
tests/lifecycle/tests/lifecycle_statefulset_scaling.go
tests/networking/helper/helper.go
tests/networking/networking_suite_test.go
tests/platformalteration/platform_alteration_suite_test.go
tests/utils/cluster/cluster.go
tests/utils/nodes/nodes.go
tests/utils/nodes/nodes_test.go

Utilize the `NodeInterface`.
Instead of passing around the entire `testclient.ClientSet`, just ask for what we need.  In this case we are only utilizing NodeInterface functionality.

Specify interface for Nodes()

---

tests/accesscontrol/helper/helper.go
tests/accesscontrol/tests/access_control_namespace.go
tests/globalhelper/installplans.go
tests/globalhelper/namespaces.go

Removed the `accesscontrol` function `DefineAndCreateInstallPlan` and utilize the same style as #524.

Reorg installPlan funcs

---

tests/observability/tests/container_logging.go
tests/observability/tests/crd_status.go
tests/observability/tests/pod_disruption_budget.go
tests/observability/tests/termination_policy.go

Remove the `qeTcFileName` global variable and align the observability suite test cases with the other suites about how `LaunchTests` is called.
We were seeing instances in parallel runs where `qeTcFileName` was empty strings and I'm thinking it has to do with the global variable.

Remove global variable TC name from observability suite

---

tests/globalhelper/rbac.go
tests/lifecycle/tests/lifecycle_persistent_volume_reclaim_policy.go
tests/lifecycle/tests/lifecycle_storage_provisioner.go

Removed the global `pvNames` variable in favor of `DeferCleanup` func calls.
The logic is that there are PVCs that are explicitly claiming the PVs so they must be deleted first in the DeferCleanup calls.

Use DeferCleanup() for PVs

---

tests/globalhelper/daemonset.go
tests/globalhelper/daemonset_test.go
tests/lifecycle/tests/lifecycle_container_startup.go
tests/lifecycle/tests/lifecycle_cpu_isolation.go
tests/lifecycle/tests/lifecycle_image_pull_policy.go
tests/lifecycle/tests/lifecycle_liveness.go

Adds some assertions after resource creation to verify that things are set that way they should be prior to running the TNF suite tests.
Bonus!  Adds some additional logic to the `isDaemonsetReady` function to help determine readiness.

Add assertions for daemonset resources

---

scripts/run-tests.sh

Ginkgo [allows](https://onsi.github.io/ginkgo/) for a flag `ginkgo --flake-attempts=N` that you can turn on and it will retry a spec with `N` retries.  I'm adding the ability to call this for our nightly runs and it is turned off by default.

Add ENABLE_FLAKY_RETRY flag

---

tests/networking/tests/networking_dpdk_cpu_pinning_exec_probe.go

See [this documentation](https://developers.redhat.com/articles/2021/08/27/using-virtual-functions-dpdk-red-hat-openshift) for more context.
I added a check for the `openshift-sriov-network-operator` namespace prior to kicking off these tests.  If it doesn't exist, skip.

Check if sriov-network-operator is installed prior to running DPDK test

---

scripts/delete-namespaces.sh
scripts/golangci-lint.sh
tests/accesscontrol/access_control_suite_test.go
tests/accesscontrol/tests/access_control_namespace.go
tests/accesscontrol/tests/access_control_security_context.go
tests/affiliatedcertification/affiliated_certification_suite_test.go
tests/affiliatedcertification/tests/affiliated_certification_container_is_certified_digest.go
tests/affiliatedcertification/tests/affiliated_certification_helm_version.go
tests/affiliatedcertification/tests/affiliated_certification_invalid_operator.go
tests/affiliatedcertification/tests/affiliated_certification_operator.go
tests/affiliatedcertification/tests/affillated_certification_helm_chart.go
tests/globalhelper/clusterrolebindings.go
tests/globalhelper/clusterroles.go
tests/globalhelper/deployment.go
tests/globalhelper/mutatingwebhook.go
tests/globalhelper/validatingwebhook.go
tests/lifecycle/lifecycle_suite_test.go
tests/lifecycle/tests/lifecycle_cpu_isolation.go
tests/networking/networking_suite_test.go
tests/observability/observability_suite_test.go
tests/observability/tests/container_logging.go
tests/observability/tests/crd_status.go
tests/operator/operator_suite_test.go
tests/operator/tests/operator_install_source.go
tests/operator/tests/operator_install_status.go
tests/operator/tests/operator_install_status_no_privileges.go
tests/platformalteration/platform_alteration_suite_test.go
tests/platformalteration/tests/platform_alteration_service_mesh.go
tests/utils/pod/pod.go

Notable changes:
- Utilizing ginkgo's `SynchronizedBeforeSuite` and `SynchronizedAfterSuite` funcs (which I should have done in the first place) for parallel run support.
- golangci-lint v1.55.0 
- Added some string consts due to golangci-lint update.
- Removed two assertion statements in `accesscontrol` suite because in OCP the `SecurityContext` pointers get automatically populated when deployments are created versus in k8s they are left `nil`.
- Lots of work in the `affiliatedcertification` suite in the helm section.  Helm leaves a lot of leftovers that we have to deal with outside of `helm uninstall` during cleanup.  This is where most of the changes happened.
- Transitioned mostly all tests in `affiliatedcertification` to use the `Serial` label.

Various changes needed for OCP to run smoothly

---

perfprofile.yml
tests/globalhelper/nodes.go
tests/globalhelper/nodes_test.go
tests/platformalteration/tests/platform_alteration_hugepages_1g.go
tests/platformalteration/tests/platform_alteration_hugepages_2m.go
tests/platformalteration/tests/platform_alteration_hugepages_config.go
tests/platformalteration/tests/platform_alteration_is_selinux_enforcing.go
tests/platformalteration/tests/platform_alteration_ocp_lifecycle.go
tests/platformalteration/tests/platform_alteration_ocp_node_os.go
tests/platformalteration/tests/platform_alteration_sysctl_config.go
tests/platformalteration/tests/platform_alteration_tainted_node_kernel.go

For reviewers:
- Created a `perfprofile.yaml` that will have to be applied to any OCP cluster running the `platformalteration` suite.  However I added logic to skip the hugepages tests if the nodes do not have hugepages enabled so it shouldn't crash if ran otherwise.
Added skips for the following tests that seem to be unstable and haven't passed even the "real" QE runs in a while:
- Change Hugepages config manually [negative]
- change sysctl config using MCO
- Untainted node
- SELinux is permissive on one node [negative]

Add hugepages logic fixes for platformalteration

---

tests/globalhelper/daemonset.go
tests/globalhelper/init.go
tests/globalhelper/networkpolicy.go
tests/globalhelper/reporthelper.go
tests/lifecycle/lifecycle_suite_test.go
tests/lifecycle/tests/lifecycle_affinity_required_pods.go
tests/lifecycle/tests/lifecycle_pod_scheduling.go
tests/networking/networking_suite_test.go
tests/networking/tests/networking_default_network.go
tests/platformalteration/platform_alteration_suite_test.go

Also removed unnecessary usage of `fmt.Sprintf` when we can just use `glog.Errorf`.

Switch glog.Fatal to glog.Error

---

tests/globalhelper/clusterroles_test.go

Adds unit test for `DeleteClusterRole()`.

Add unit tests for clusterroles.go

---

tests/globalhelper/init_test.go

Add unit tests for functions in init.go.  There are a few functions in this file that use Ginkgo/Gomega commands and/or try to access that can be addressed later in another PR for testing.

Add unit tests for init.go

---

.github/workflows/pre-main.yml

Splits up the multiple items that the original CI YAML performed into actual separate jobs.

Split CI into different jobs

---

tests/utils/poddisruptionbudget/poddisruptionbudget_test.go

Adds some simple sanity tests to make sure what we are trying to define actually matches expected output.

Add utils/pdb unit tests

---

tests/utils/cluster/cluster.go
tests/utils/cluster/cluster_test.go
tests/utils/nodes/nodes.go

- Adjust `IsClusterStable()` to check the value after performing the Update().
- Remove the `Patch()` func from the `setUnSchedulableValue` function.  Use `Update()` instead which is more user friendly.
- Add unit tests for `IsClusterStable()`.

Remove Patch() from IsClusterStable() func path

---

tests/lifecycle/tests/lifecycle_readiness.go

Just a simple assertion that there is no readiness probe for this daemonset.

Assert no readiness probe

---

tests/networking/helper/helper.go
tests/utils/nodes/nodes.go
tests/utils/nodes/nodes_test.go

Remove duplicate func `isMasterNode`.  Added unit tests surrounding the remaining funcs.

Add unit tests for nodes package

---

tests/operator/helper/helper.go

Adds a log for showing the current phase of the CSV during the `Eventually()` loop waiting for it to become ready.

Dump current phase of the operator during Eventually()

---

scripts/run-tests.sh

https://onsi.github.io/ginkgo/#spec-parallelization
Explicitly set the number of procs spawned during parallel execution to 4 instead of allowing ginkgo to determine based on CPU.  Trying to figure out why we are seeing errors like:
https://github.com/test-network-function/cnf-certification-test/actions/runs/6844412413/job/18626977288

Reduce the number of procs for parallel

---

scripts/delete-namespaces.sh

We shouldn't need to delete this prior to running the tests because we purposefully Skip() tests in the lifecycle and accesscontrol suite because the operator doesn't exist.

Remove cr-scale-operator-system from delete-namespaces script

---

scripts/run-tests.sh
tests/affiliatedcertification/affiliated_certification_suite_test.go
tests/lifecycle/lifecycle_suite_test.go
tests/observability/observability_suite_test.go
tests/operator/operator_suite_test.go

https://onsi.github.io/ginkgo/#parallel-suite-setup-and-cleanup-synchronizedbeforesuite-and-synchronizedaftersuite
These function calls were in the wrong spot.

Adjust SynchronizedAfterSuite

---

tests/utils/pod/pod.go

The original implementation was overwriting any req/limit that was previosly set for the other resources. For instance, test cases doing this didn't work properly:
```
pod.RedefineWithCPUResources(testPod, "1", "1")
pod.RedefineWithMemoryResources(testPod, "512Mi", "512Mi")
```
The call to pod.RedefineWithMemoryResources() was zero-ing the cpu req/limits that was just set before ("1", "1") as it was creating a new empty container.Resources field (corev1.ResourceRequirements{}).
The new implementations don't overwrite other reqs/limits values, they just set/overwrite the corresponding ones (cpu/mem).
The affected test cases were passing until now because a bug in the cert suite code in the function AreCPUResourcesWholeUnits() that was wrongly returning "true" when the cpu reqs/limit were …

Fixed pod's cpu & mem resource setters helpers.

---

.github/workflows/qe.yml
tests/globalhelper/pod.go
tests/performance/tests/rt_app_no_exec_probes.go
tests/platformalteration/tests/platform_alteration_base_image.go
tests/platformalteration/tests/platform_alteration_boot_params.go
tests/platformalteration/tests/platform_alteration_sysctl_config.go

The QE repo has reached a point where I believe it is stable enough to turn on the PR checks again starting with the QE repo itself and soon the TNF suite repo.

Enable PR checks against test suite

---

.github/workflows/qe.yml
tests/globalhelper/reporthelper.go

Related to: 
- https://github.com/test-network-function/cnf-certification-test/pull/1675
- https://github.com/test-network-function/cnf-certification-test/pull/1666
Depends-On: https://github.com/test-network-function/cnf-certification-test/pull/1675

Switch to 1-to-1 result struct mapping

---

.github/workflows/qe.yml

Turn on the QE PR checks for PRs against the `ginkgo_removal` branch.
We can remove this when we finally merge everything together.

Enable QE PR checks for ginkgo_removal

---

tests/accesscontrol/tests/access_control_nodeport_service.go

In the `ginkgo_removal` branch, we mark a test as skipped if there are no services found.

Switch to Skipped expected state for nodeport test

---

README.md
tests/accesscontrol/tests/access_control_bpf_capability_check.go
tests/accesscontrol/tests/access_control_container_host_port.go
tests/accesscontrol/tests/access_control_container_non-root_user.go
tests/accesscontrol/tests/access_control_ipc_lock_capability_check.go
tests/accesscontrol/tests/access_control_namespace_resource_quota.go
tests/accesscontrol/tests/access_control_net_admin_capability_check.go
tests/globalhelper/daemonset.go
tests/globalhelper/daemonset_test.go
tests/globalhelper/init.go
tests/globalhelper/nodes.go
tests/lifecycle/tests/lifecycle_container_startup.go
tests/lifecycle/tests/lifecycle_cpu_isolation.go
tests/lifecycle/tests/lifecycle_image_pull_policy.go
tests/lifecycle/tests/lifecycle_liveness.go
tests/lifecycle/tests/lifecycle_pod_scheduling.go
tests/lifecycle/tests/lifecycle_readiness.go
tests/lifecycle/tests/lifecycle_startup_probe.go
tests/networking/tests/networking_undeclared_container_ports_usage.go
tests/observability/tests/termination_policy.go
tests/performance/tests/rt_app_no_exec_probes.go
tests/performance/tests/rt_isolated_cpu_pool.go
tests/utils/config/config.go

Changes:
- Change `TNF_LOG_LEVEL` from trace to debug for the logging changes made in the suite in [PR#1663](https://github.com/test-network-function/cnf-certification-test/pull/1663)
- Added a number of `By("Create deployment")` statements that give more context to what the test is actually doing.
- Some modifications to the `isDaemonsetReady` logic.  It now mirrors what we do in the test suite repo where we compare the number of nodes (`GetNumberOfNodes()`) to the number of desired scheduled pods in the daemonset.  This makes everything much more stable/happy.
Marked WIP until I have gotten through all of the tests.

Various ginkgo_removal fixes

---

tests/accesscontrol/helper/helper.go

In all other suites, we use `tsparams` as the shorthand for the parameters file.  This is just to increase consistency.

Use 'tsparams' to be consistent

---

config/config.yaml
tests/globalhelper/runhelper.go
tests/utils/config/config.go
tests/utils/container/container.go

Removed previous docker engine check as it is not valid when using docker-podman on linux. Replace previous mechanism with a simple environent variable

Add container engine variable

---

.github/workflows/pre-main.yml

#622 introduced the ginkgo_removal branch QE PR testing but didn't enable the unit testing which is allowing failures to sneak past.

Add 'ginkgo_removal' branch for unit testing

---

.github/workflows/qe.yml

- add a check-all-dependencies-are-merged pipeline to prevent merging when a dependency isn't merged.

qe.yml: use extra-dirs in the depends-on-action

---

tests/accesscontrol/helper/helper.go
tests/networking/helper/helper.go
tests/utils/deployment/deployment.go
tests/utils/nad/nad.go
tests/utils/service/service.go
tests/utils/service/service_test.go

These funcs shouldn't return the same object they are modifying.

Adjust redefine funcs to not return their own objects

---

tests/manageability/parameters/parameters.go

Related to: https://github.com/test-network-function/cnf-certification-test-partner/pull/385 
https://hub.docker.com/layers/library/httpd/2.4.58/images/sha256-448ce9c60d2ac0e8f779ce871b06df6452c30dae74f725d5694502da9c902036?context=explore

Update httpd to v2.4.58

---

tests/manageability/parameters/parameters.go
tests/manageability/tests/containers_image_tag.go

To avoid `ImagePullBackoff` failures in the manageability suite, I pushed my own version of the httpd image to my own quay repo.  The billerica lab is hitting the rate limit from Docker Hub.

Switch httpd image to custom repo

---

tests/platformalteration/tests/platform_alteration_boot_params.go

In our OCP environments, we do not have any `machineConfig` objects to test.  So the test expects there to be some but there aren't any deployed in the cluster.  The test suite code marks this as skipped now due to changes in the `ginkgo_removal` effort.

Change expected state for MCO test

---

tests/operator/tests/operator_install_source.go
tests/operator/tests/operator_install_status.go
tests/operator/tests/operator_install_status_no_privileges.go

Follow up to the `ginkgo_removal` branch work.  These changes are needed for the OCP scenario tests to pass for the operator suite.

Fix operator suite

---

tests/platformalteration/tests/platform_alteration_boot_params.go
tests/platformalteration/tests/platform_alteration_hugepages_1g.go
tests/platformalteration/tests/platform_alteration_hugepages_2m.go
tests/platformalteration/tests/platform_alteration_is_redhat_release.go
tests/platformalteration/tests/platform_alteration_is_selinux_enforcing.go
tests/platformalteration/tests/platform_alteration_tainted_node_kernel.go

We shouldn't be cordoning nodes while other tests are running.

Adjust tainted node test to be ran in 'Serial'

---

tests/affiliatedcertification/affiliated_certification_suite_test.go
tests/globalhelper/catalogsources.go
tests/globalhelper/catalogsources_test.go
tests/operator/operator_suite_test.go

If the OCP cluster we are running QE against doesn't have the following, throw an error before they can run the test suite as a prerequisite:
```
NAMESPACE               NAME                  DISPLAY               TYPE   PUBLISHER   AGE
openshift-marketplace   certified-operators   Certified Operators   grpc   Red Hat     88d
openshift-marketplace   community-operators   Community Operators   grpc   Red Hat     88d
openshift-marketplace   redhat-marketplace    Red Hat Marketplace   grpc   Red Hat     88d
openshift-marketplace   redhat-operators      Red Hat Operators     grpc   Red Hat     88d
```

Safeguard against missing catalog sources

---

tests/globalhelper/rbac.go
tests/utils/crd/crd.go

Seems like this parameters should have been pointers when redefining properties within them.

Use pointers in Redefine funcs

---

.github/workflows/qe.yml

Similar to: https://github.com/test-network-function/cnf-certification-test/pull/1812
Adds retries to the `make build-image-local` command to smooth out failures.

Add retries for 'make build-image-local'

---

tests/networking/tests/networking_default_network.go
tests/networking/tests/networking_multus_links.go

The `networking` suite ICMP tests that utilize daemonsets are banking on their being more than one node in the cluster.  I added checks for the number of nodes and changed the expected state of the test based on that.
For testing, I was using OpenShift Local (CRC) on a Mac.

Add checks for node count prior to icmp tests using daemonset

---

tests/globalhelper/nodes.go
tests/lifecycle/tests/lifecycle_affinity_required_pods.go
tests/lifecycle/tests/lifecycle_cpu_isolation.go
tests/lifecycle/tests/lifecycle_pod_high_availability.go
tests/lifecycle/tests/lifecycle_pod_scheduling.go
tests/lifecycle/tests/lifecycle_storage_provisioner.go

Changes:
- Add `nodes.IsClusterOverCommitted()` funcs to check if cluster is even able to spawn CPU isolation cluster.
- Adjust various tests that do not act correctly when there is only a single node to test against (think scaling tests).

Add lifecycle suite flexibility for single node clusters

---

tests/networking/tests/networking_multus_links.go

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1853
This negative test is designed to fail even on Single Node.  The logic I added in #679 does not apply.

Fix networking suite single node

---

.github/workflows/qe.yml

Use /mnt (sdb) for docker storage. Same as
https://github.com/test-network-function/cnf-certification-test/pull/1857

Github CI: Step to use /mnt for docker storage

---

.github/workflows/qe.yml
tests/globalhelper/helper.go
tests/globalhelper/runhelper.go
tests/globalparameters/globalparameters.go

- Modify the `tnf_config` that we build to pass in variables for the collector.
- Add `JOB_ID` environment variable to pass the github job ID in as part of the `partnerName`.

Enable collector for QE runs

---

tests/performance/helper/helper.go

Similar to #697 
Making these limits and requests smaller to better allow for smaller environments to run QE.
This is tested against CRC.

Modify resources for performance suite tests

---

tests/affiliatedcertification/tests/affiliated_certification_operator.go

#665 changed these to skipped, however there has been a change upstream (see PR [here](https://github.com/test-network-function/cnf-certification-test/pull/1901)) in the test suite which now just marks items as `failed` instead of `skipped` if not ran which is the expected result.
These only fail on OCP so that seems to be when this broke.

Adjust skipped to failed expected affilated-certification

---

tests/affiliatedcertification/tests/affiliated_certification_operator.go

Follow up to #706 with another test case that is now expected failed due to: https://github.com/test-network-function/cnf-certification-test/pull/1871

Switch expected output for no labels

---

.github/workflows/qe.yml

Since the `cnf-certification-test` repo already builds the unstable images on merge, we shouldn't need to build the image here as well.
This shaves off a few minutes of each run since we are already building the image for upstream.

Instead of building images use pre-built unstable

---

tests/affiliatedcertification/tests/affiliated_certification_helm_version.go
tests/affiliatedcertification/tests/affillated_certification_helm_chart.go

Adds validation to check whether or not helm v3 is actually installed.
Also, it seems that the helm charts for hashicorp vault have changed and needed an update.
https://developer.hashicorp.com/vault/docs/platform/k8s/helm

Add helm validation and change vault repo

---

tests/affiliatedcertification/parameters/parameters.go

Looks like the `cockroachdb` image is no longer tagging 'latest' images.
https://catalog.redhat.com/software/containers/cockroachdb/cockroach/596691854b339a3561489ac2?architecture=amd64&container-tabs=gti&image=6601dced1d7d6222ddd1412f

Use specific certified image

---

scripts/clean-marketplace.sh

Adds a simple script to clean up the `openshift-marketplace` namespace.
I will use this script in our nightlies to help smooth out errors seen such as: 
https://github.com/test-network-function/cnf-certification-test/actions/runs/8776950576

Add openshift-marketplace cleanup script

---

scripts/run-tests.sh

I'm not entirely sure what's going on quite yet on the self-hosted runners, but it seems that we are maybe overloading the runner box kicking off the QE tests.  I'm going to temporarily limit the procs to 4 threads to see if it makes it more stable.

Temporarily limit procs to 4

---

tests/lifecycle/tests/lifecycle_pod_high_availability.go

I'm not exactly sure why this wasn't there in the first place to be honest.

Add 'Serial' label to high availability tests

---

tests/affiliatedcertification/parameters/parameters.go

`nginx-ingress-operator` has a new version v2.2.1

Update operator versions

---

tests/affiliatedcertification/affiliated_certification_suite_test.go
tests/globalhelper/catalogsources.go
tests/operator/operator_suite_test.go

Reverts #751 
I also removed the check for the `"redhat-operators", "redhat-marketplace"` catalog sources because they don't seem to be relevant to the passing of the operator or affiliated suite test cases.

Re-enable catalog source precheck

---

.github/workflows/qe.yml

Related to: https://github.com/test-network-function/cnf-certification-test/pull/2078

Add 10 minute timeout for waiting for all pods to be ready

---

config/config.yaml
tests/globalhelper/runhelper.go
tests/utils/config/config.go

Modified `LaunchTests()` func to either run against the binary or the image depending on the config.  Default path is still the image.

Add 'use_binary' option

---

tests/affiliatedcertification/tests/affiliated_certification_invalid_operator.go

These tests were previously skipped and were never re-enabled.

Re-enable previously skipped tests

---

tests/affiliatedcertification/affiliated_certification_suite_test.go
tests/globalhelper/operator.go
tests/operator/operator_suite_test.go

In the `affiliatedcertification` and `operator` suites, automatically apply the certified-operator catalog source.

Deploy certified-operators catalogsource automatically

---

tests/platformalteration/tests/platform_alteration_tainted_node_kernel.go

We shouldn't restart the only node in the cluster during this test.  Applicable to CRC, SNO, etc.

Skip tainted node test when only single node

---

.golangci.yml
tests/globalhelper/pod.go
tests/globalhelper/runhelper.go
tests/operator/parameters/parameters.go
tests/operator/tests/operator_common.go
tests/operator/tests/operator_non_root.go
tests/operator/tests/operator_pod_automount_token.go
tests/operator/tests/operator_read_only_filesystem.go
tests/operator/tests/operator_run_as_userid.go

Based on changes coming from: https://github.com/test-network-function/cnf-certification-test/pull/1967

New operator tests w real tests

---

scripts/run-tests.sh
tests/platformalteration/parameters/parameters.go

Limited the number of default allowed procs to 16.
Switched the jitesoft/nginx image to use `stable` which is now multiarch:
https://quay.io/repository/jitesoft/nginx?tab=tags

Limit procs by default

---

tests/operator/tests/operator_pod_automount_token.go

Marking this test case as an expected failure because the default service account deployed by the nginx operator leaves the SA automount token field nil which is 'true' by default.  This is wrong and needs to be explicitly set false.

Adjust operator automount test for SA

---

tests/accesscontrol/tests/access_control_pod_service_account.go

These expected failed tests should have the [negative] string in their It() blocks.

Add missing [negative] labels

---

tests/globalhelper/operator.go
tests/operator/operator_suite_test.go
tests/operator/parameters/parameters.go
tests/operator/tests/operator_install_source.go
tests/utils/operator/operator.go
tests/utils/operator/operator_test.go

Deploys the `cluster-logging` cluster-wide operator with a subscription in another namespace, separate from the namespace under test.  In this case, it installs the subscription in `openshift-logging` namespace while the test is workload is being deployed in `randomNamespace` per usual.
Also adds some setup code in `DeployRHOperatorSource` which deploys the `redhat-operators` catalog source if missing.
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2407

Add cluster logging test to operator suite

---

tests/operator/helper/helper.go
tests/operator/tests/operator_crd_openapi_schema.go
tests/operator/tests/operator_crd_versioning.go
tests/operator/tests/operator_install_source.go
tests/operator/tests/operator_install_status.go
tests/operator/tests/operator_install_status_no_privileges.go
tests/operator/tests/operator_non_root.go
tests/operator/tests/operator_pod_automount_token.go
tests/operator/tests/operator_read_only_filesystem.go
tests/operator/tests/operator_run_as_userid.go
tests/operator/tests/operator_semantic_versioning.go
tests/utils/operator/operator.go

Add the logic back to deploy the operators into each test case that needs them, and then add a boolean for targetNamespaces for operator group.

Add operator deployment back

---

go.mod
go.sum
vendor/github.com/openshift-kni/eco-goinfra/pkg/rbac/clusterrole.go
vendor/github.com/openshift-kni/eco-goinfra/pkg/rbac/clusterrolebinding.go
vendor/github.com/openshift-kni/eco-goinfra/pkg/rbac/role.go
vendor/github.com/openshift-kni/eco-goinfra/pkg/rbac/rolebinding.go
vendor/modules.txt

Remove `eco-goinfra` from the replace section of the go.mod so dependabot can update this.

Update eco-goinfra to latest commit

---

tests/globalhelper/catalogsources.go

Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2484
Utilizes the new `slices.Contains` functionality built into Go 1.21.

Switch to slices.Contains

---

tests/affiliatedcertification/helper/helper.go
tests/affiliatedcertification/tests/affiliated_certification_invalid_operator.go
tests/affiliatedcertification/tests/affiliated_certification_operator.go
tests/globalhelper/init.go
tests/globalhelper/operator.go
tests/operator/helper/helper.go
tests/operator/parameters/parameters.go
tests/operator/tests/operator_crd_openapi_schema.go
tests/operator/tests/operator_crd_versioning.go
tests/operator/tests/operator_install_source.go
tests/operator/tests/operator_install_status.go
tests/operator/tests/operator_install_status_no_privileges.go
tests/operator/tests/operator_multiple_installed.go
tests/operator/tests/operator_semantic_versioning.go

Adding tests for the new multiple-same-operators test case.
This PR includes a positive and negative test.
The positive test involves installing the same operator.version in two different namespaces.  This is a valid case.
The negative test involves installing different operator.version's in two different namespaces.  This is an invalid case.

operator: add test for multiple-same-operators

---

tests/globalhelper/operator.go
tests/operator/parameters/parameters.go
tests/operator/tests/operator_bundle_image.go
tests/operator/tests/operator_multiple_installed.go

Adds a positive and negative test for the new `operator-bundle-count` test.
Marked WIP until https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2549 merges.

operator: add bundle-count test

---

.github/workflows/qe.yml

This looks like a typo from when we changed over to the new org.

Adjust typo

---

tests/accesscontrol/tests/access_control_container_non-root_user_id.go

Skipped two test cases related to securityContext.runAsUser field as they both should fail in kind clusters. The reason is those fields are automatically set by SCC in OCP clusters, whereas in kind clusters will be kept as nil in both pod and container level, which is not comformant to best practices.
They started failing in certsuite qe workflow jobs for the PR that fixes the implementation of the runAsUser check:
https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2617

Skip two access-control test cases.

---

tests/accesscontrol/tests/access_control_sys_admin_capability_check.go
tests/utils/deployment/deployment.go
tests/utils/deployment/deployment_test.go

These two test cases cover this certsuite fix PR:
https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2352
Without that certsuite fix, the tc `access-control-sys-admin-capability-check` failed also when the forbidden capability SYS_ADMIN was set in the drop list, which is wrong.
These new QE tcs make sure the certsuite tc passes in that scenario.

acccess_control_sys_admin_capability ts: add two positive tcs.

---

tests/globalhelper/catalogsources.go

Gets rid of having to manually update the logic whenever a new OCP version is released.  Just create the index and move on.

Redo logic for creating community operator index

---

.github/dependabot.yml
.github/workflows/pre-main.yml
.github/workflows/qe.yml
.golangci.yml
go.mod
scripts/install-latest-go.sh

Related to: 
- https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2806
- https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2795

Update Go to v1.24.0; dependabot config update

---

.github/workflows/pre-main.yml
.golangci.yml

#1080 seems to hate on these settings in the .golangci.yml

Fix golangci-lint-action

---

tests/operator/tests/operator_install_status_no_privileges.go

Switch the following tests to install `cloudbees-ci` instead of `kiali`.
- one operator with clusterPermissions and resourceNames [negative]
- two operators, one with clusterPermissions and resourceNames

fix operator-install-status test; remove kiali

---

.golangci.yml
tests/accesscontrol/helper/helper_test.go
tests/globalhelper/clusterroles_test.go
tests/globalhelper/namespaces_test.go
tests/globalhelper/nodes_test.go
tests/operator/tests/operator_single_or_multi_namespaced_allowed_in_tenant_namespaces.go
tests/utils/nodes/nodes_test.go

Follow up to #1084 
Run the `single-or-multi-namespaced-allowed-in-tenant-namespaces` test in Serial and also add some cleanup for the namespace prior to running.  There was a leftover `cluster-logging` namespace that was leftover during a failed run so it was throwing the tests off.

Add logic for namespace cleanup and Serial

---

tests/globalhelper/init.go
tests/platformalteration/parameters/parameters.go
tests/platformalteration/tests/platform_alteration_cluster_operator_health.go
tests/platformalteration/tests/platform_alteration_cluster_operator_health_test.go

Adds tests for: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2787

platform-alteration: Add positive test for OCP-only clusters

---

.github/workflows/qe-ocp.yml
.github/workflows/qe.yml
tests/globalhelper/daemonset.go
tests/globalhelper/deployment.go
tests/globalhelper/pod.go
tests/globalhelper/replicaset.go
tests/globalhelper/statefulset.go

Adds some modifications to the IsReady funcs to speed up the detection of ready objects.  Adds an OCP nightly run using quick-ocp.
* [`.github/workflows/qe-ocp.yml`](diffhunk://#diff-c13b14c9b655fb5672a795fc5e1c27be6d66587dfa15f814f0ccf78e4a50277fR1-R93): Added a new workflow for QE OCP Testing on Ubuntu-hosted runners. This includes matrix testing for multiple suites, environment variable setup, dependency installation, OCP cluster setup, and test execution against both images and binaries.
* [`.github/workflows/qe.yml`](diffhunk://#diff-a90bd711e6964ed07f1bd5524ede4bbbdc4a51f8baab54f295f8ec3fbccb8cbdL2): Removed an unnecessary blank line to clean up the file.
* [`tests/globalhelper/daemonset.go`](diffhunk://#diff-11cb7135b810afc282ac7d99c79a622b1d02db3cc98a06c0d9b5c3048a484854L40-R46): …

Speed up IsReady funcs; add OCP nightly

---

.github/workflows/qe-ocp.yml
.github/workflows/qe.yml
tests/globalhelper/helper.go
tests/lifecycle/tests/lifecycle_deployment_scaling.go
tests/lifecycle/tests/lifecycle_pod_recreation.go
tests/lifecycle/tests/lifecycle_statefulset_scaling.go

This pull request introduces changes to support CRC (Code Ready Containers) clusters in the testing framework. It includes the addition of a utility function to detect CRC clusters and updates to skip certain tests that are incompatible with CRC clusters. Additionally, a workflow file has been commented out to disable pull request triggers.
* [`tests/globalhelper/helper.go`](diffhunk://#diff-e1c500cd9f2c78d57abb90392858cb8048992645b2eb5693eb098951dff49adaR368-R412): Added a new function `IsCRCCluster()` to detect CRC clusters using multiple methods, including domain patterns, node configurations, and labels.
* [`tests/lifecycle/tests/lifecycle_deployment_scaling.go`](diffhunk://#diff-130e6ce5d8e09b25db8a15193eab1e4909d123386c65f35ffcd78e5b8c7f5571R56-R58): Updated the deployment scaling …

Skip these intrusive tests on CRC environments

---

.github/workflows/pull-images.yml
.github/workflows/qe-ocp.yml
scripts/run-tests.sh
tests/affiliatedcertification/parameters/parameters.go
tests/affiliatedcertification/tests/affiliated_certification_invalid_operator.go
tests/affiliatedcertification/tests/affiliated_certification_operator.go
tests/globalhelper/packagemanifest.go
tests/operator/helper/helper.go
tests/operator/parameters/parameters.go
tests/operator/tests/operator_bundle_image.go
tests/operator/tests/operator_crd_openapi_schema.go
tests/operator/tests/operator_crd_versioning.go
tests/operator/tests/operator_install_source.go
tests/operator/tests/operator_install_status.go
tests/operator/tests/operator_install_status_no_privileges.go
tests/operator/tests/operator_multiple_installed.go
tests/operator/tests/operator_semantic_versioning.go
tests/operator/tests/operator_single_or_multi_namespaced_allowed_in_tenant_namespaces.go

This pull request introduces several updates across workflows, test scripts, and operator-related code, primarily focusing on replacing references to the `nginx-ingress-operator` with the `grafana-operator` and enhancing operator query functionality. Additionally, the changes improve logging and test execution details. Below is a breakdown of the most important changes:
* Replaced the `nginx-ingress-operator` image with the `grafana-operator` image in the `.github/workflows/pull-images.yml` file.
* Enabled the `pull_request` trigger for the `QE OCP Testing` workflow and commented out an unused test suite in the matrix. [[1]](diffhunk://#diff-c13b14c9b655fb5672a795fc5e1c27be6d66587dfa15f814f0ccf78e4a50277fL5-R6) [[2]](diffhunk://#diff-c13b14c9b655fb5672a795fc5e1c27be6d66587dfa15f814f0ccf78e …

Replace busted operators

---

.github/workflows/qe-ocp.yml

This pull request updates the GitHub Actions workflow to ensure that the `qe-ocp-testing` job only runs on pull requests originating from the main repository, not from forks.
* [`.github/workflows/qe-ocp.yml`](diffhunk://#diff-c13b14c9b655fb5672a795fc5e1c27be6d66587dfa15f814f0ccf78e4a50277fR15-R16): Added a conditional check (`if`) to the `qe-ocp-testing` job to prevent it from running on pull requests from forked repositories.

Restrict OCP CI runs from forks

---

tests/affiliatedcertification/tests/affiliated_certification_invalid_operator.go
tests/affiliatedcertification/tests/affiliated_certification_operator.go
tests/globalhelper/packagemanifest.go
tests/operator/tests/operator_bundle_image.go
tests/operator/tests/operator_crd_openapi_schema.go
tests/operator/tests/operator_crd_versioning.go
tests/operator/tests/operator_install_source.go
tests/operator/tests/operator_install_status.go
tests/operator/tests/operator_install_status_no_privileges.go
tests/operator/tests/operator_semantic_versioning.go
tests/operator/tests/operator_single_or_multi_namespaced_allowed_in_tenant_namespaces.go

We should fail out before attempting to spawn operators that don't exist in catalog sources.  This will make problems easier to diagnose.

Log and Fail() if operator does not exist in packagemanifests

---

tests/globalhelper/catalogsources.go
tests/globalhelper/helper.go
tests/globalhelper/installplans.go
tests/globalhelper/nodes.go
tests/globalhelper/runhelper.go
tests/globalhelper/storageclasses.go

Fixes some linting failures with the new version of golangci-lint.
* `tests/globalhelper/helper.go`:
- Updated `IsKindCluster` to use `exec.CommandContext` with `context.Background()` instead of `exec.Command`.
- Updated `IsCRCCluster` to use `exec.CommandContext` with `context.Background()` instead of `exec.Command`.
* `tests/globalhelper/runhelper.go`:
- Imported the `context` package to enable the use of `context.Background()`.
- Updated `launchTestsViaBinary` to use `exec.CommandContext` with `context.Background()` instead of `exec.Command`.
- Updated `launchTestsViaImage` to use `exec.CommandContext` with `context.Background()` instead of `exec.Command`.

Fix context lint failure

---

.github/workflows/qe-ocp.yml

Don't fail on forked PRs, just skip gracefully if the pull secret is not available.
- **Added check for `CRC_PULL_SECRET`:** A new step (`Check for CRC Pull Secret`) verifies if the `CRC_PULL_SECRET` secret is available. If absent, it outputs a warning and sets a flag (`has-secret=false`) to skip subsequent OCP-related steps.
- **Conditional OCP cluster setup:** The `Setup up OCP cluster` step now runs only when the secret is available (`if: steps.check-secret.outputs.has-secret == 'true`).
- **Conditional pod readiness check:** The step to wait for pods to be ready is executed only if the secret is available (`if: steps.check-secret.outputs.has-secret == 'true`).
- **Conditional test execution:** The test-running step is skipped unless the secret is available (`if: …

Skip QE OCP tests gracefully if missing pull-secret

---

.github/workflows/qe-ocp.yml

Disable image runs that run against `quick-ocp` as there seems to be some sort of upstream change in our actions runners that is limiting our memory now.

Disable image runs from nightlies

---

.github/workflows/qe.yml

Based on changes from #1189 this adds a prebuild step to built the `certsuite` localtest image from scratch.

Prebuild image for QE PR runs
